gigs:
  - title: Ziggo Dome
    date: 2015-11-04T00:00:00.000Z
    location: Utrecht
    url: 'http://www.ziggo.com'
  - title: Ziggo Dome
    date: 2015-11-05T00:00:00.000Z
    location: Amsterdam
    url: 'http://www.ziggo.com'
  - title: Ziggo Dome in de grote hal
    date: 2015-12-06T00:00:00.000Z
    location: Benidorm
    url: 'http://www.ziggo.com'