gigs:
  - title: 'Piano duo Mike del Ferro & Jeroen van Veen'
    date: 2016-01-27T20:00:00.000Z
    location: Amsterdam (NL)
    venue: Splendor
    url: www.splendoramsterdam.com
  - title: CD recordings with Metropole Orchestra
    date: 2016-02-03T10:00:00.000Z
    location: 'Hilversum, NL'
    venue: Muziekcentrum Omroep
    url: ''
  - title: 'Mike del Ferro "opera meets jazz"'
    date: 2016-02-06T20:00:00.000Z
    location: De Rode Hoed
    venue: Amsterdam
    url: 'http://www.rodehoed.nl'
  - title: Mike del Ferro / Palle Danielson / Anders Kjellberg
    date: 2016-02-12T08:00:00.000Z
    location: 'Gothenburg, SE'
    venue: Jazz Club Nefertiti
    url: ''
  - title: Mike del Ferro trio
    date: 2016-02-16T19:00:00.000Z
    location: Moscow
    venue: Estrada Theatre
    url: 'http://www.teatr-estrada.ru/index.php/component/content/article?id=142'
  - title: Lecture
    date: 2016-02-18T17:00:00.000Z
    location: Tilburg (NL)
    venue: Fontys Hogeschool
    url: ''
  - title: 'Mike del Ferro and the Brasilia Symphonic orchestra, Opera meets Jazz'
    date: 2016-03-08T20:00:00.000Z
    location: Brasilia (B)
    venue: TBA
    url: ''
  - title: Mike del Ferro and Mike Boddé pianoduo
    date: 2016-04-15T20:00:00.000Z
    location: Amsterdam (NL)
    venue: De Kleine Komedie
    url: www.dekleinekomedie.nl
  - title: Mike del Ferro and Mike Boddé pianoduo
    date: 2016-04-16T20:00:00.000Z
    location: Amsterdam (NL)
    venue: De Kleine Komedie
    url: www.dekleinekomedie.nl
  - title: Kuwait Jazz festival
    date: 2016-04-28T20:00:00.000Z
    location: TBA
    venue: Kuwait City
    url: ''
  - title: Mike del Ferro with the Metropole orchestra
    date: 2016-05-08T11:00:00.000Z
    location: Amsterdam (NL)
    venue: 'Concertgebouw, main hall ( 11am! )'
    url: www.concertgebouw.nl
  - title: Mike del Ferro / Jeroen van Veen/ Malgosia Fiebig
    date: 2016-08-22T20:00:00.000Z
    location: Utrecht
    venue: Dom Tower
    url: ''
  - title: 'Piano Duo Mike Boddé & Mike del Ferro'
    date: 2017-03-10T20:00:00.000Z
    location: Rotterdam
    venue: De Doelen
    url: www.dedoelen.nl