gigs:
  - title: 'Mike del Ferro trio & Claron McFadden'
    date: 2017-01-06 20:00:00
    location: De Toonzaal
    venue: Den Bosch (NL)
    url: www.detoonzaal.nl
  - title: Mike del Ferro trio
    date: 2017-01-14 20:00:00
    location: 10/14 Club
    venue: Warszaw-Poland
    url:
  - title: Mike del Ferro trio
    date: 2017-01-17 19:30:00
    location: NOSPR
    venue: Katowice-Poland
    url: 'http://www.nospr.org.pl/en/concerts/627/wtorkowy-klub-jazzowy-mike-del-ferro-trio-feat-ceumar'
  - title: Mike del Ferro / Mike Boddé pianoduo
    date: 2017-03-10 20:30:00
    location: De Doelen
    venue: Rotterdam-NL
    url: www.dedoelen.nl
  - title: Mike del Ferro trio / Claron McFadden - opera meets jazz
    date: 2017-01-07 20:00:00
    location: Splendor
    venue: Amsterdam
    url: www.splendoramsterdam.com
  - title: Mike del Ferro
    date: 2016-12-10 20:30:00
    location: TBA
    venue: Antwerp (B)
    url:
  - title: Mike del Ferro trio
    date: 2016-12-11 15:00:00
    location: Jazzclub
    venue: Vorden (NL)
    url:
  - title: Tour Pakistan -Feb 16-25
    date: 2017-02-16 20:00:00
    location: tba
    venue: Pakistan
    url:
  - title: Mike del Ferro trio with Niladri Kumar and Deborah Carter
    date: 2017-01-09 19:00:00
    location: TBA
    venue: Sharja (Dubai)
    url:
  - title: 'Tour Sweden, jan 31-feb 8 more details soon'
    date: 2017-01-31 15:00:00
    location: Sweden
    venue:
    url:
  - title: Mike del Ferro trio
    date: 2017-03-12 15:00:00
    location: Jazzclub
    venue: Valkenswaard (NL)
    url:
  - title: 'Artist in Residence, Luzern Jazzschool Switzerland j, January 18-20'
    date: 2017-01-18 00:00:00
    location:
    venue:
    url:
  - title: 'Mike del Ferro & Claron McFadden'
    date: 2017-03-26 15:00:00
    location: De Steenakker
    venue: Haps (Nijmegen)
    url: 'http://www.desteenakker.nl/zondag-26-maart-2017-mike-del-ferro-en-claron-mcfadden/'
  - title: 'Mike del Ferro & Claron McFadden'
    date: 2017-05-20 08:00:00
    location: Tindall Villa
    venue: Bussum (NL)
    url: 'http://www.tindal.nl/Tindal/20170520.html'
  - title: '4 pianists/4 grand pianos!'
    date: 2017-01-22 17:30:00
    location: Beauforthuis
    venue: Austerlitz (Zeist) NL
    url: www.beauforthuis.nl
  - title: 'Duo Mike Boddé & Mike del Ferro, Mike kwadraat'
    date: 2017-01-26 20:00:00
    location: Beauforthuis
    venue: Austerlitz (Zeist) NL
    url: www.beauforthuis.nl