gigs:
  - title: Haiti Jazz Festival with James Germain
    date: 2020-01-18 19:30:00
    location: Port au Prince
    venue: Haiti
    url: 'http://papjazzhaiti.org/'
  - title: 'with Mbuso Khoza, Matthias Spilmann'
    date: 2019-12-14 20:30:00
    location: Munganga
    venue: Amsterdam (NL)
    url: 'https://www.munganga.nl'
  - title: Meditative Concert with  Mesmerizing Visuals
    date: 2019-11-10 15:30:00
    location: Steenakker
    venue: Haps (Nijmegen) NL
    url: 'http://www.desteenakker.nl'
  - title: >-
      Lying down Concert: Mike del Ferro & Jeroen van Veen, Canto Ostinato and
      beyond
    date: 2019-11-07 20:00:00
    location: Wilminktheater
    venue: Enschede  (NL)
    url: >-
      https://www.wilminktheater.nl/programma/!/8162/jeroen-van-veen-mike-del-ferro/canto-ostinato-and-beyond-ligconcert/
  - title: Mike del Ferro solo recital
    date: 2019-12-01 15:00:00
    location: MCO Gebouw
    venue: Hilversum (NL)
    url: 'https://www.mcogebouw.nl'
  - title: With Jeroen van Veen - Canto Ostinato & beyond
    date: 2019-12-07 20:00:00
    location: Agnietenhof Theater
    venue: Tiel (NL)
    url: www.agnietenhof.nl
  - title: Mike del Ferro trio
    date: 2019-09-29 15:00:00
    location: OBA Zuid Oost
    venue: Amsterdam CNL)
    url:
  - title: Mike del Ferro and Jeroen van Veen- Canto Ostinato and Beyond
    date: 2020-01-09 20:00:00
    location: De Meerse
    venue: Hoofddorp (NL)
    url: 'https://www.demeerse.nl/'
  - title: Slow Water Music - Mezmerizing Visuals with live Concert
    date: 2019-11-09 20:00:00
    location: Ten Club
    venue: Amsterdam
    url: 'https://www.facebook.com/events/743919619382916/'
  - title: Mike del Ferro with Mbuso Khoza from South Africa
    date: 2019-12-15 15:00:00
    location: Fenix Music Factory
    venue: Rotterdam (NL)
    url: 'http://www.fenixmusicfactory.nl/concerten/'
  - title: Masterclass - self management and networking for Musicians
    date: 2019-12-04 14:00:00
    location: jazzschool/jazzcampus
    venue: Basel (Switzerland)
    url: www.jazzcampus.com