gigs:
  - title: Solo recital and piano duo with Jeroen Van Veen
    date: 2015-11-22T07:00:00.000Z
    location: 'Belgrade, Rs'
    venue: Keyboarddays
    url: www.keyboarddays.com
  - title: Mike del Ferro trio
    date: 2016-01-22T08:00:00.000Z
    location: 'Gothenburg, SE'
    venue: Jazz Club Nefertiti
    url: ''
  - title: CD recordings with Metropole Orchestra
    date: 2016-02-03T10:00:00.000Z
    location: 'Hilversum, NL'
    venue: Muziekcentrum Omroep
    url: ''
  - title: Mike del Ferro trio
    date: 2016-02-06T20:00:00.000Z
    location: 'Zeist, NL'
    venue: De Bovenkamer
    url: ''
  - title: Mike del Ferro with the Metropole orchestra
    date: 2016-05-07T15:00:00.000Z
    location: Hilversum
    venue: 'MCO gebouw (afternoon concert!)'
    url: www.mcogebouw.nl
  - title: Mike del Ferro with the Metropole orchestra
    date: 2016-05-08T11:00:00.000Z
    location: Amsterdam (NL)
    venue: 'Concertgebouw, main hall ( 11am! )'
    url: www.concertgebouw.nl