gigs:
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-02 20:15:00
    location: Muziekgebouw Frits Philips
    venue: Eindhoven (NL)
    url: www.muziekgebouweindhoven.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-08 20:15:00
    location: De Vereeniging
    venue: Nijmegen (NL)
    url: www.stadsschouwburgendevereeniging.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-16 20:00:00
    location: De Harmonie
    venue: Leeuwarden (NL)
    url: www.harmonie.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-20 20:15:00
    location: De Beun
    venue: Heiloo
    url: www.theaterdebeun.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-23 20:30:00
    location: Stadstheater
    venue: Zoetermeer
    url: www.stadstheater.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-24 20:30:00
    location: Agora theater
    venue: Lelystad
    url: www.agora-lelystad.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-09 20:30:00
    location: De Lawei
    venue: Drachten
    url: www.lawei.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-16 20:15:00
    location: Singer
    venue: Laren (NL)
    url: www.singerlaren.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-23 20:15:00
    location: Het Klooster / Theater
    venue: Woerden (NL)
    url: www.kloosterwoerden.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-28 08:30:00
    location: Goudse Schouwburg
    venue: Gouda (NL)
    url: www.goudseschouwburg.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-30 20:30:00
    location: Griffioen Theater
    venue: Amstelveen
    url: www.griffioen.vu.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-31 20:30:00
    location: Parkstad Theater
    venue: Heerlen (NL)
    url: www.parkstadlimburgtheaters.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-04-04 20:15:00
    location: De Veste
    venue: Delft (NL)
    url: www.theaterdeveste.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-04-07 20:00:00
    location: Schouwburg Odeon
    venue: Zwolle (NL)
    url: www.zwolsetheaters.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-04-20 20:30:00
    location: Energiehuis
    venue: Dordrecht
    url: www.kunstmin.nl
  - title: Mike del Ferro trio with Shota Ishikawa & Sebastiaan Kaptein
    date: 2018-03-01 20:00:00
    location: TBA
    venue: 'Kobe, Japan'
    url: 'https://www.facebook.com/dai.murata.3'
  - title: Mike del Ferro and Wim Dijkgraaf
    date: 2018-01-21 00:00:00
    location: Plus etage
    venue: Baarle Nassau
    url:
  - title: Mike del Ferro trio with Shota Ishikawa & Sebastiaan Kaptein
    date: 2018-03-02 20:00:00
    location: TBA
    venue: 'Kobe, Japan'
    url: 'https://www.facebook.com/dai.murata.3'
  - title: Duo Mike Boddé and Mike del Ferro-Mike Kwadraat
    date: 2018-03-10 20:00:00
    location: Paradox
    venue: Tilburg
    url: www.paradoxtilburg.nl
  - title: Mike del Ferro & Mbuso Khoza
    date: 2018-01-05 19:00:00
    location: Headroom
    venue: Durban (South Africa)
    url: 'https://www.facebook.com/events/146881809300816/'
  - title: 'Mike del Ferro & friends, more details soon'
    date: 2018-02-17 20:30:00
    location: Munganga
    venue: Amsterdam
    url: www.munganga.nl
  - title: Mike del Ferro trio with Shota Ishikawa & Sebastiaan Kaptein
    date: 2018-03-03 20:30:00
    location: TBA
    venue: Kobe (Japan)
    url: 'https://www.facebook.com/dai.murata.3'
  - title: >-
      Mike del Ferro , Mbuso Khoza and the KZN Heritage Choir (afternoon
      concert!)
    date: 2018-01-07 14:00:00
    location: Kwadukuzu Town Hall
    venue: Durban (South Africa)
    url: 'http://www.isupportdoyou.com/'
  - title: Mike del Ferro trio & Trijntje Oosterhuis
    date: 2018-01-20 20:30:00
    location: Splendor
    venue: Amsterdam (NL)
    url: www.splendoramsterdam.com
  - title: Recordings with Mbuso Khoza and the KZN Heritage Choir
    date: 2018-01-08 00:00:00
    location: SABC Studios
    venue: Durban (South Africa)
    url:
  - title: Mike del Ferro trio
    date: 2018-03-20 20:00:00
    location: Luxor theater
    venue: Zutphen (NL)
    url: 'https://www.facebook.com/jazzinluxor'
  - title: Mike del Ferro trio (afternoon concert!)
    date: 2018-03-25 15:00:00
    location: Rosa Spier Huis
    venue: Laren (NL Noord Holland)
    url:
  - title: Guest appearance with Flamenco Masters Jaco Abel & Julian Heredia
    date: 2018-01-19 20:30:00
    location: Munganga
    venue: Amsterdam (NL)
    url:
  - title: Canto Ostinato meets Jazz with Sandra & Jeroen van Veen
    date: 2018-02-03 20:00:00
    location: Pernissimo
    venue: Pernis (NL)
    url: www.pernissimo.nl
  - title: Mike del Ferro trio
    date: 2018-02-04 15:00:00
    location: TBA
    venue: Münster (Germany)
    url: