gigs:
  - title: 'Tour Japan, May 2019, more details soon'
    date: 2019-05-12 20:00:00
    location:
    venue: Japan
    url:
  - title: Mike del Ferro & Dodo Kis -Bimhuis Lab
    date: 2019-01-28 20:30:00
    location: Bimhuis
    venue: Amsterdam (NL)
    url: 'https://www.bimhuis.com'
  - title: Mike del Ferro & Maya Fridman
    date: 2019-02-16 20:30:00
    location: Munganga
    venue: Amsterdam (NL)
    url: 'https://www.munganga.nl'
  - title: 'Tour Norway, more details soon'
    date: 2019-05-04 20:00:00
    location: Norway
    venue:
    url:
  - title: >-
      Mike del Ferro & André Heuvelman, Infinite Now: Concerts with beautiful
      Visuals
    date: 2019-02-08 20:00:00
    location: Pianino
    venue: Den Haag (NL)
    url: 'https://www.facebook.com/pianinotheater/'
  - title: >-
      Mike del Ferro & André Heuvelman, Infinite Now: Concerts with beautiful
      Visuals
    date: 2019-02-02 20:30:00
    location: Splendor
    venue: Amsterdam
    url: www.splendoramsterdam.com
  - title: 'with Jeroen van Veen, Canto Ostinato and beyond'
    date: 2019-02-09 20:00:00
    location: Pernissimo
    venue: Pernis (NL)
    url: www.pernissimo.org
  - title: Mike del Ferro & Friends
    date: 2019-03-23 20:00:00
    location: Hot Clube
    venue: Lisbon (Portugal)
    url: 'https://www.hcp.pt'
  - title: Mike del Ferro trio and Andre Heuvelman
    date: 2019-03-07 21:00:00
    location: Le poisson Rouge
    venue: New York City (US)
    url: 'https://www.lpr.com'
  - title: Mike del Ferro tba
    date: 2019-03-22 20:00:00
    location: Hot Clube
    venue: Lissabon (Portugal)
    url: 'https://www.hcp.pt'
  - title: 'Tour USA , more details soon'
    date: 2019-02-28 13:00:00
    location: USA
    venue:
    url:
  - title: 'Duo with Jeroen van Veen, Canto Ostinato and Beyond'
    date: 2019-02-15 20:00:00
    location: Tenclub
    venue: Amsterdam
    url:
  - title: with Josee Koning
    date: 2019-02-17 20:00:00
    location: Gelderlandfabriek
    venue: Culemborg (NL)
    url: >-
      https://www.degelderlandfabriek.nl/events/event/muziek-jam-jazz-pizza-josee-koning-mike-del-ferro/