gigs:
  - title: 'Duo Claron McFadden& Mike del Ferro'
    date: 2016-08-12T20:00:00.000Z
    location: Radar beyond music festival
    venue: 'Varna, Bulgaria'
    url:
  - title: Mike del Ferro / Jeroen van Veen/ Malgosia Fiebig
    date: 2016-08-22T20:00:00.000Z
    location: Dom Tower
    venue: Utrecht (NL)
    url:
  - title: 'Mike del Ferro & Pekka Pylkannen'
    date: 2016-10-29T20:00:00.000Z
    location: Birdseye
    venue: Basel (CH)
    url: www.birdseye.ch
  - title: 'Mike del Ferro trio & Claron McFadden'
    date: 2017-01-06T20:00:00.000Z
    location: De Toonzaal
    venue: Den Bosch (NL)
    url: www.detoonzaal.nl
  - title: 'Mike del Ferro & Pekka Pylkannen'
    date: 2016-10-28T20:00:00.000Z
    location: Birds Eye
    venue: Basel (CH)
    url: www.birdseye.ch
  - title: '"networking and selfmanagement for musicians"'
    date: 2016-10-26T14:30:00.000Z
    location: Jazzschule
    venue: Basel-Switserland
    url:
  - title: Mike del Ferro trio
    date: 2017-01-14T20:00:00.000Z
    location: 10/14 Club
    venue: Warszaw-Poland
    url:
  - title: Mike del Ferro trio
    date: 2017-01-17T20:00:00.000Z
    location: TBA
    venue: Katowice-Poland
    url:
  - title: Mike del Ferro / Mike Boddé pianoduo
    date: 2017-02-10T20:30:00.000Z
    location: De Doelen
    venue: Rotterdam-NL
    url: www.dedoelen.nl
  - title: Mike del Ferro / Claron McFadden - opera meets jazz
    date: 2017-01-07T20:00:00.000Z
    location: Splendor
    venue: Amsterdam
    url: www.splendoramsterdam.com
  - title: 'Mike del Ferro & Claron McFadden'
    date: 2016-11-04T20:00:00.000Z
    location: De Morgenster
    venue: Hilversum (NL)
    url: 'http://www.seinconcerten.nl/'
  - title: 'Mike del Ferro, Mola Sylla, Pernell Saturnino and Christian Galvez'
    date: 2016-08-01T19:00:00.000Z
    location: Flores Festival
    venue: 'Medellin, Colombia'
    url:
  - title: Piano duo Mike Boddé and Mike del Ferro
    date: 2016-07-07T20:00:00.000Z
    location: Noord Zie Jazz
    venue: Rotterdam
    url: 'http://www.noordziejazz.nl/#Bergsingelkerk'