gigs:
  - title: with Johan van der Linden (afternoon concert!)
    date: 2019-09-08 14:00:00
    location: Brink
    venue: Muiderberg (NL)
    url: 'https://www.swingopdebrink.nl/klassiek-op-de-brink/'
  - title: 'Slow Water Music: Meditative Concert with Mesmerizing Visuals'
    date: 2019-11-09 20:00:00
    location: Tenclub
    venue: Amsterdam
    url: 'https://www.tenclub.nl/'
  - title: with Andre Heuvelman - Nachtgeluiden
    date: 2019-08-30 19:30:00
    location: 'Oude Kapschuur, Oude Papeweg 33'
    venue: Wassenaar (NL)
    url: 'https://andreheuvelman.com'
  - title: with Gabriel Grossi
    date: 2019-09-21 20:30:00
    location: Bimhuis
    venue: Amsterdam (NL
    url: www.bimhuis.nl
  - title: 'with Rogerio Boccato, Mbuso Khoza, Matthias Spilmann'
    date: 2019-12-14 20:30:00
    location: Munganga
    venue: Amsterdam (NL)
    url: 'https://www.munganga.nl'
  - title: Meditative Concert with  Mesmerizing Visuals
    date: 2019-11-10 15:30:00
    location: Steenakker
    venue: Haps (Nijmegen) NL
    url: 'http://www.desteenakker.nl'
  - title: >-
      Lying down Concert: Mike del Ferro & Jeroen van Veen, Canto Ostinato and
      beyond
    date: 2019-11-07 20:00:00
    location: Wilminktheater
    venue: Enschede  (NL)
    url: >-
      https://www.wilminktheater.nl/programma/!/8162/jeroen-van-veen-mike-del-ferro/canto-ostinato-and-beyond-ligconcert/
  - title: Mike del Ferro solo recital
    date: 2019-12-01 15:00:00
    location: MCO Gebouw
    venue: Hilversum (NL)
    url: 'https://www.mcogebouw.nl'
  - title: With Jeroen van Veen - Canto Ostinato & beyond
    date: 2019-12-07 20:00:00
    location: Agnietenhof Theater
    venue: Tiel (NL)
    url: www.agnietenhof.nl
  - title: 'Mike del Ferro with Andrea Caruso, Classic meets Jazz (afternoon concert)'
    date: 2019-09-29 15:00:00
    location: TBA
    venue: Groningen (NL)
    url:
  - title: Mike del Ferro and Jeroen van Veen- Canto Ostinato and Beyond
    date: 2020-01-09 20:00:00
    location: De Meerse
    venue: Hoofddorp (NL)
    url: 'https://www.demeerse.nl/'
  - title: with Jeroen van Veen
    date: 2019-09-13 19:00:00
    location: TBA
    venue: Culemborg (NL)
    url: 'http://www.pianoculemborg.nl/'
  - title: >-
      with Maya Fridman, Sebastian Netta, Uli Wentzlaff- Classic meets Jazz
      (afternoon concert!!)
    date: 2019-08-25 15:00:00
    location: Berkelfestival
    venue: Gescher - Münster area (Germany)
    url: 'http://wuw.netta.de'
  - title: >-
      Slow Water Music - Live Concert with Mesmerizing Visuals of Water and
      Light-with Jeroen van Veen, Andre Heuvelman and Frans de Rond
    date: 2019-08-22 20:00:00
    location: Beauforthuis
    venue: Austerlitz (NL
    url: www.beauforthuis.nl
  - title: 'Mike del Ferro Trio, Albania Jazz festival'
    date: 2019-10-12 20:00:00
    location: Rogner Hotel
    venue: Tirana (Albania)
    url:
  - title: Masterclass - self management and networking for Musicians
    date: 2019-12-04 14:00:00
    location: jazzschool/jazzcampus
    venue: Basel (Switzerland)
    url: www.jazzcampus.com
  - title: Nachtgeluiden (Night Sounds)- with Andre Heuvelman
    date: 2019-09-06 20:00:00
    location: Open Air Theatre / Forest
    venue: Kwintelooijen (NL)
    url: 'https://www.andreheuvelman.nl'
  - title: Canto Ostinato - Dom Tower -with Jeroen van Veen and Malgosia Fiebig
    date: 2019-08-19 20:00:00
    location: Dom Tower
    venue: Utrecht
    url: 'https://www.klokkenspelvereniging.nl/'