gigs:
  - title: Yoga & Soundscapes in the early morning 7am!! With André Heuvelman
    date: 2018-10-21 07:00:00
    location:
    venue: Rotterdam (NL)
    url: >-
      http://www.rotterdamsphilharmonisch.nl/nl/concerten/andré-heuvelman-yoga-soundscapes
  - title: Mike Boddé & Mike del Ferro
    date: 2018-12-21 20:00:00
    location: Lantaren Venster
    venue: Rotterdam (NL)
    url: 'http://www.lantarenvenster.nl'
  - title: Mike del Ferro trio & David Linx
    date: 2018-12-15 20:30:00
    location: Splendor
    venue: Amsterdam (NL)
    url: 'https://www.splendoramsterdam.com'
  - title: Masterclass
    date: 2018-11-14 15:00:00
    location: Jazz Schule
    venue: Basel (CH)
    url:
  - title: Mike del Ferro & Mike Boddé & Mystery Guest
    date: 2018-10-13 20:00:00
    location: Pianoduo festival - Amstelkerk
    venue: Amsterdam (NL)
    url: 'https://www.pianoduofestival.nl'
  - title: Mike del Ferro & Mike Boddé - Mike Kwadraat
    date: 2018-11-17 20:30:00
    location: Porgy & Bess
    venue: Terneuzen (NL)
    url: 'http://www.porgyenbess.nl'
  - title: 'Mike del Ferro, Rogerio Boccato, Hermine Deurloo, Joris Teepe'
    date: 2018-10-30 20:00:00
    location: De Oosterpoort
    venue: Groningen (NL)
    url: >-
      https://www.de-oosterpoort.nl/programma/joris-teepe-presents-nyctg-rogerio-boccato-30-oktober/
  - title: 'Mike Boddé & Mike del Ferro, Mike Kwadraat'
    date: 2018-12-21 20:00:00
    location: Lantaren Venster
    venue: Rotterdam (NL)
    url: 'https://www.lantarenvenster.nl/programma/mike-kwadraat/'
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-11 20:00:00
    location: Meervaart
    venue: Amsterdam (NL)
    url:
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-03 20:00:00
    location: De Flint
    venue: Amersfoort (NL
    url:
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-04 20:00:00
    location: De Vereeniging
    venue: Nijmegen (NL)
    url:
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-05 20:00:00
    location: Theater
    venue: Hoorn (NL)
    url:
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-09 20:00:00
    location: Nieuwe Luxor
    venue: Rotterdam (NL)
    url:
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-10 20:00:00
    location: Theater
    venue: Enschede (NL)
    url:
  - title: Mike del Ferro & David Linx
    date: 2018-12-15 20:00:00
    location: Splendor
    venue: Amsterdam
    url: www.splendoramsterdam.nl