gigs:
  - title: 'Mike del Ferro & Claron McFadden'
    date: 2016-06-10T20:00:00.000Z
    location: De Steenakker
    venue: Haps (NL)
    url: www.desteenakker.nl
  - title: 'Mike del Ferro & Jeroen van Veen'
    date: 2016-06-03T16:00:00.000Z
    location: Mafra
    venue: Lisbon-Portugal
    url: ''
  - title: Kuwait Jazz festival
    date: 2016-04-28T20:00:00.000Z
    location: TBA
    venue: Kuwait
    url: ''
  - title: Mike del Ferro with the Metropole orchestra
    date: 2016-05-08T11:00:00.000Z
    location: 'Concertgebouw, main hall ( 11am! )'
    venue: Amsterdam (NL)
    url: 'http://www.concertgebouw.nl'
  - title: 'Mike del Ferro trio & Claron McFadden'
    date: 2016-05-13T20:00:00.000Z
    location: Beauforthuis
    venue: Austerlitz (Zeist/NL)
    url: 'http://www.beauforthuis.nl'
  - title: 'Mike del Ferro / Claron McFadden, stings and horns Metropole'
    date: 2016-06-09T20:00:00.000Z
    location: Scheldetheater
    venue: Terneuzen (NL)
    url: ''
  - title: The music of Queen Mike del Ferro / Jeroen van Veen/ Malgosia Fiebig
    date: 2016-06-11T20:00:00.000Z
    location: Cathedral
    venue: Brugge (Belgium)
    url: ''
  - title: Mike del Ferro / Jeroen van Veen/ Malgosia Fiebig
    date: 2016-08-22T20:00:00.000Z
    location: Dom Tower
    venue: Utrecht (NL)
    url: ''
  - title: 'Mike del Ferro & Pekka Pylkannen'
    date: 2016-10-29T20:00:00.000Z
    location: Birdseye
    venue: Basel (CH)
    url: www.birdseye.ch
  - title: 'Mike del Ferro trio & Claron McFadden'
    date: 2017-01-06T20:00:00.000Z
    location: De Toonzaal
    venue: Den Bosch (NL)
    url: www.detoonzaal.nl
  - title: 'Mike del Ferro & Pekka Pylkannen'
    date: 2016-10-28T20:00:00.000Z
    location: Birds Eye
    venue: Basel (CH)
    url: www.birdseye.ch
  - title: '"networking and selfmanagement for musicians"'
    date: 2016-10-27T15:00:00.000Z
    location: Jazzschule
    venue: Basel-Switserland
    url: ''
  - title: Canto Ostinato meets Jazz (with Jeroen and Sandra van Veen)
    date: 2016-06-18T20:00:00.000Z
    location: TBA
    venue: Shikodra-Albania
    url: ''
  - title: Canto Ostinato for 10 pianists at Festival Classique
    date: 2016-06-12T16:00:00.000Z
    location: tba
    venue: The Hague (NL)
    url: ''
  - title: Canto Ostinato meets Jazz (with Jeroen and Sandra van Veen)
    date: 2016-06-17T20:00:00.000Z
    location: Opera House
    venue: Tirana (Albania)
    url: ''
  - title: Mike del Ferro trio
    date: 2017-01-14T20:00:00.000Z
    location: 10/14 Club
    venue: Warszaw-Poland
    url: ''
  - title: Mike del Ferro trio
    date: 2017-01-17T20:00:00.000Z
    location: TBA
    venue: Katowice-Poland
    url: ''
  - title: Mike del Ferro / Mike Boddé pianoduo
    date: 2017-02-10T20:30:00.000Z
    location: De Doelen
    venue: Rotterdam-NL
    url: www.dedoelen.nl
  - title: Mike del Ferro / Jeroen van Veen / Malgosia Fiebig
    date: 2016-06-11T20:00:00.000Z
    location: Cathedral
    venue: Brugge-Belgium
    url: ''