gigs:
  - title: Mike del Ferro/Marcio Bahia/Andre Vasconcellos
    date: 2016-03-12T19:15:00.000Z
    location: Teatro de Câmara of Cidade das Artes
    venue: Rio de Janeiro-Brazil
    url: ''
  - title: 'South America tour, Brazil, Argentina, Colombia'
    date: 2016-03-03T00:00:00.000Z
    location: ''
    venue: ''
    url: ''
  - title: 'Mike del Ferro and the Brasilia Symphony orchestra,'
    date: 2016-03-08T19:00:00.000Z
    location: Teatro Pedro Calmon
    venue: Brasilia (Brazil)
    url: ''
  - title: Mike del Ferro
    date: 2016-03-10T20:00:00.000Z
    location: SESC-Teatro Newton Rossi
    venue: Ceilandia (Brazil)
    url: ''
  - title: Mike del Ferro trio with Marcio Bahia and Andre Vasconcellos
    date: 2016-03-19T20:00:00.000Z
    location: Cafe com letras
    venue: Belo Horizonte (Brazil)
    url: ''
  - title: Mike del Ferro trio
    date: 2016-03-28T20:00:00.000Z
    location: tba
    venue: Medellin (Colombia)
    url: ''
  - title: Mike del Ferro and Mike Boddé pianoduo/video artist Mirthe Dokter
    date: 2016-04-15T20:00:00.000Z
    location: De Kleine Komedie
    venue: Amsterdam (NL)
    url: 'http://www.dekleinekomedie.nl'
  - title: Mike del Ferro and Mike Boddé pianoduo/video artist Mirthe Dokter
    date: 2016-04-16T20:00:00.000Z
    location: De Kleine Komedie
    venue: Amsterdam (NL)
    url: 'http://www.dekleinekomedie.nl'
  - title: Kuwait Jazz festival
    date: 2016-04-28T20:00:00.000Z
    location: TBA
    venue: Kuwait
    url: ''
  - title: Mike del Ferro with the Metropole orchestra
    date: 2016-05-08T11:00:00.000Z
    location: 'Concertgebouw, main hall ( 11am! )'
    venue: Amsterdam (NL)
    url: 'http://www.concertgebouw.nl'
  - title: 'Mike del Ferro trio & Claron McFadden'
    date: 2016-05-13T20:00:00.000Z
    location: Beauforthuis
    venue: Austerlitz (Zeist/NL)
    url: 'http://www.beauforthuis.nl'
  - title: 'Mike del Ferro / Claron McFadden, stings and horns Metropole'
    date: 2016-06-09T20:00:00.000Z
    location: Scheldetheater
    venue: Terneuzen (NL)
    url: ''
  - title: The music of Queen Mike del Ferro / Jeroen van Veen/ Malgosia Fiebig
    date: 2016-06-11T20:00:00.000Z
    location: Cathedral
    venue: Brugge (Belgium)
    url: ''
  - title: Mike del Ferro / Jeroen van Veen/ Malgosia Fiebig
    date: 2016-08-22T20:00:00.000Z
    location: Dom Tower
    venue: Utrecht (NL)
    url: ''
  - title: Mike del Ferro  trio
    date: 2016-03-23T21:00:00.000Z
    location: Cocina de Culturas
    venue: Cordoba (Argentina)
    url: ''
  - title: Masterclass and Concert
    date: 2016-03-04T16:00:00.000Z
    location: TBA
    venue: Goiana (Brazil)
    url: ''