gigs:
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-02 20:15:00
    location: Muziekgebouw Frits Philips
    venue: Eindhoven (NL)
    url: www.muziekgebouweindhoven.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-08 20:15:00
    location: De Vereeniging
    venue: Nijmegen (NL)
    url: www.stadsschouwburgendevereeniging.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-16 20:00:00
    location: De Harmonie
    venue: Leeuwarden (NL)
    url: www.harmonie.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-20 20:15:00
    location: De Beun
    venue: Heiloo
    url: www.theaterdebeun.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-23 20:30:00
    location: Stadstheater
    venue: Zoetermeer
    url: www.stadstheater.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-24 20:30:00
    location: Agora theater
    venue: Lelystad
    url: www.agora-lelystad.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-09 20:30:00
    location: De Lawei
    venue: Drachten
    url: www.lawei.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-16 20:15:00
    location: Singer
    venue: Laren (NL)
    url: www.singerlaren.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-23 20:15:00
    location: Het Klooster / Theater
    venue: Woerden (NL)
    url: www.kloosterwoerden.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-28 08:30:00
    location: Goudse Schouwburg
    venue: Gouda (NL)
    url: www.goudseschouwburg.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-30 20:30:00
    location: Griffioen Theater
    venue: Amstelveen
    url: www.griffioen.vu.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-31 20:30:00
    location: Parkstad Theater
    venue: Heerlen (NL)
    url: www.parkstadlimburgtheaters.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-04-04 20:15:00
    location: De Veste
    venue: Delft (NL)
    url: www.theaterdeveste.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-04-07 20:00:00
    location: Schouwburg Odeon
    venue: Zwolle (NL)
    url: www.zwolsetheaters.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-04-20 20:30:00
    location: Energiehuis
    venue: Dordrecht
    url: www.kunstmin.nl
  - title: Mike del Ferro trio with Jeroen Vierdag & Sebastiaan Kaptein
    date: 2017-11-23 08:00:00
    location: New Combo
    venue: 'Fukuoka, Japan'
    url: 'http://newcombo.sakura.ne.jp/live11.html'
  - title: Mike del Ferro and Wim Dijkgraaf
    date: 2018-01-21 00:00:00
    location: Plus etage
    venue: Baarle Nassau
    url:
  - title: Mike del Ferro trio with Jeroen Vierdag & Sebastiaan Kaptein
    date: 2017-11-24 20:00:00
    location: 'Garaman Hall, Ginoza, Okinawa (Japan)'
    venue: Okinawa (Japan)
    url: 'http://garaman.jp/sf'
  - title: Duo Mike Boddé and Mike del Ferro-Mike Kwadraat
    date: 2018-03-10 20:00:00
    location: Paradox
    venue: Tilburg
    url: www.paradoxtilburg.nl
  - title: Duo Jeroen van Veen & Mike del Ferro
    date: 2017-12-09 20:00:00
    location: Ostade Theater
    venue: Amsterdam
    url:
  - title: Mike del Ferro & Jeroen van Veen
    date: 2017-11-16 20:30:00
    location: Roode Bioscoop
    venue: Amsterdam
    url: www.roodebioscoop.nl
  - title: Mike del Ferro & Mike Boddé
    date: 2017-11-17 20:30:00
    location: Roode Bioscoop
    venue: Amsterdam
    url: www.roodebioscoop.nl
  - title: Mike del Ferro & Remy van Kesteren
    date: 2017-11-18 20:30:00
    location: Roode Bioscoop
    venue: Amsterdam
    url: www.roodebioscoop.nl
  - title: Mike del Ferro trio with Jeroen Vierdag & Sebastiaan Kaptein
    date: 2017-11-29 20:00:00
    location: Haretara Sorani Mame Maite
    venue: Tokyo (Japan)
    url: 'http://mameromantic.com'
  - title: >-
      4 weeks South Africa, Masterclasses, Concerts and Recordings, more details
      soon
    date: 2017-12-13 00:00:00
    location:
    venue: South Africa
    url:
  - title: Mike del Ferro trio with Jeroen Vierdag & Sebastiaan Kaptein
    date: 2017-11-28 20:00:00
    location: Mam'selle
    venue: Fukuroi (Japan)
    url: 'http://music.geocities.jp/mamselle33'
  - title: Mike del Ferro trio with Jeroen Vierdag & Sebastiaan Kaptein
    date: 2017-11-30 20:00:00
    location: Up
    venue: Koga (Japan)
    url: 'http://www.ups-jazz.com/index.shtml'
  - title: Mike del Ferro trio
    date: 2018-03-25 15:00:00
    location: Rosa Spier Huis
    venue: Laren (NL Noord Holland)
    url:
  - title: Guest appearance with Flamenco Masters Jaco Abel & Julian Heredia
    date: 2018-01-19 20:30:00
    location: Munganga
    venue: Amsterdam (NL)
    url:
  - title: Canto Ostinato meets Jazz with Sandra & Jeroen van Veen
    date: 2018-02-03 20:00:00
    location: Pernissimo
    venue: Pernis (NL)
    url: www.pernissimo.nl
  - title: Mike del Ferro trio
    date: 2018-02-04 03:00:00
    location: TBA
    venue: Münster (Germany)
    url:
  - title: Jeroen van Veen & Mike del Ferro at the Barn
    date: 2018-02-11 03:00:00
    location: Baambrugge (NL)
    venue: TBA
    url:
  - title: Mike del Ferro trio with Jeroen Vierdag & Sebastiaan Kaptein
    date: 2017-11-25 20:00:00
    location: Hirado City Hall
    venue: Nagasaki (Japan)
    url:
  - title: Mike del Ferro trio with Jeroen Vierdag & Sebastiaan Kaptein
    date: 2017-11-27 08:00:00
    location: Mr.Kenny's
    venue: Nagoya (Japan)
    url: 'https://www.mrkennys.com/schedule/'