gigs:
  - title: 'Mike del Ferro & Claron McFadden'
    date: 2017-05-20 08:00:00
    location: Tindall Villa
    venue: Bussum (NL)
    url: 'http://www.tindal.nl/Tindal/20170520.html'
  - title: 'Mike Boddé & Mike del Ferro, Mike Kwadraat'
    date: 2017-08-21 08:00:00
    location: Concertgebouw
    venue: Amsterdam
    url: www.concertgebouw.nl
  - title: 'Jeroen van Veen & Mike del Ferro piano duo'
    date: 2017-05-26 20:00:00
    location: Pianino theater ( in the Moof building)
    venue: Den Haag
    url:
  - title: 'Duo Remy van Kesteren & Mike del Ferro'
    date: 2017-04-14 20:30:00
    location: Splendor
    venue: Amsterdam
    url: www.splendoramsterdam.com
  - title: Mike del Ferro trio
    date: 2017-07-15 20:00:00
    location: 'Krakow Jazzfestival, Poland'
    venue: Krakow
    url:
  - title: 'Duo Jeroen van Veen & Mike del Ferro (morning concert!)'
    date: 2017-07-30 00:00:00
    location: Kasteeltuin Middachten
    venue: Rheden (NL)
    url:
  - title: with Jeroen van Veen
    date: 2017-09-29 20:00:00
    location: Breda
    venue: Orgelstorm festival
    url:
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-02 20:00:00
    location: 'Eindhoven, more details soon'
    venue:
    url:
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-08 00:00:00
    location: 'Nijmegen, more details will follow'
    venue:
    url:
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-16 20:00:00
    location: 'Leeuwarden, more details will follow'
    venue:
    url:
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-20 20:00:00
    location: 'Heiloo, more details will follow'
    venue:
    url:
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-23 20:00:00
    location: 'Zoetermeer, more details will follow'
    venue:
    url:
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-24 20:00:00
    location: 'Lelystad, more details will follow'
    venue:
    url:
  - title: 'Clinic "Networking and Selfmanagement for Musicians" by Mike del Ferro'
    date: 2017-04-06 14:00:00
    location: Amsterdam
    venue: Splendor
    url: www.facebook.com/mikedelferro3
  - title: 'Mike del Ferro, solo recital'
    date: 2017-04-09 16:00:00
    location: Den Haag (the Hague)
    venue: Universal center for Sufism
    url: