gigs:
  - title: with Jeroen Van Veen
    date: 2015-11-22T00:00:00.000Z
    location: 'Belgrade, Rs'
    venue: Pianofestival
    url: ''
  - title: Trio del Ferro / Kjellberg / Mori
    date: 2015-11-05T00:00:00.000Z
    location: 'Inom Vallgraven, Sweden'
    venue: Jazzklubben Nefertiti
    url: ''
  - title: with Metropole Orkest
    date: 2015-12-06T00:00:00.000Z
    location: 'Hilversum, NL'
    venue: Muziekcentrum Omroep
    url: ''