gigs:
  - title: with Johan van der Linden (afternoon concert!)
    date: 2019-09-08 14:00:00
    location: Brink
    venue: Muiderberg (NL)
    url: 'https://www.swingopdebrink.nl/klassiek-op-de-brink/'
  - title: 'With Maya Fridman and others, Details TBA'
    date: 2019-10-17 20:00:00
    location: TBA
    venue:
    url:
  - title: Haiti Jazz Festival with James Germain
    date: 2020-01-18 19:30:00
    location: Port au Prince
    venue: Haiti
    url: 'http://papjazzhaiti.org/'
  - title: with Gabriel Grossi
    date: 2019-09-21 20:30:00
    location: Bimhuis
    venue: Amsterdam (NL
    url: www.bimhuis.nl
  - title: 'with Rogerio Boccato, Mbuso Khoza, Matthias Spilmann'
    date: 2019-12-14 20:30:00
    location: Munganga
    venue: Amsterdam (NL)
    url: 'https://www.munganga.nl'
  - title: Meditative Concert with  Mesmerizing Visuals
    date: 2019-11-10 15:30:00
    location: Steenakker
    venue: Haps (Nijmegen) NL
    url: 'http://www.desteenakker.nl'
  - title: >-
      Lying down Concert: Mike del Ferro & Jeroen van Veen, Canto Ostinato and
      beyond
    date: 2019-11-07 20:00:00
    location: Wilminktheater
    venue: Enschede  (NL)
    url: >-
      https://www.wilminktheater.nl/programma/!/8162/jeroen-van-veen-mike-del-ferro/canto-ostinato-and-beyond-ligconcert/
  - title: Mike del Ferro solo recital
    date: 2019-12-01 15:00:00
    location: MCO Gebouw
    venue: Hilversum (NL)
    url: 'https://www.mcogebouw.nl'
  - title: With Jeroen van Veen - Canto Ostinato & beyond
    date: 2019-12-07 20:00:00
    location: Agnietenhof Theater
    venue: Tiel (NL)
    url: www.agnietenhof.nl
  - title: 'Mike del Ferro with Andrea Caruso, Classic meets Jazz (afternoon concert)'
    date: 2019-09-29 15:00:00
    location: Brouwerij Martinus
    venue: Groningen (NL)
    url: >-
      http://www.stichtingjazzingroningen.nl/agenda/martinus-klassieke-affaire-mike-del-ferro-andrea-caruso/
  - title: Mike del Ferro and Jeroen van Veen- Canto Ostinato and Beyond
    date: 2020-01-09 20:00:00
    location: De Meerse
    venue: Hoofddorp (NL)
    url: 'https://www.demeerse.nl/'
  - title: with Jeroen & Sandra van Veen
    date: 2019-09-13 19:00:00
    location: Barbara Kerk
    venue: Culemborg (NL)
    url: 'http://www.pianoculemborg.nl/jubileum-concert/'
  - title: 'Mike del Ferro Trio, Albania Jazz festival'
    date: 2019-10-12 20:00:00
    location: Rogner Hotel
    venue: Tirana (Albania)
    url:
  - title: Masterclass - self management and networking for Musicians
    date: 2019-12-04 14:00:00
    location: jazzschool/jazzcampus
    venue: Basel (Switzerland)
    url: www.jazzcampus.com
  - title: Nachtgeluiden (Night Sounds)- with Andre Heuvelman
    date: 2019-09-06 00:00:00
    location: Open Air Theatre / Forest
    venue: Kwintelooijen (NL)
    url: 'https://www.andreheuvelman.nl'