gigs:
  - title: with Johan van der Linden (afternoon concert!)
    date: 2019-09-08 00:00:00
    location: Brink
    venue: Muiderberg (NL)
    url: 'https://www.swingopdebrink.nl/klassiek-op-de-brink/'
  - title: Mike del Ferro & Mbuso Khoza
    date: 2019-06-28 23:00:00
    location: the Chairman
    venue: Durban (South Africa)
    url: 'http://www.thechairmanlive.com'
  - title: Mike del Ferro and Yasuhito Mori
    date: 2019-05-24 20:00:00
    location: Body and Soul
    venue: Tokyo- Japan
    url: www.bodyandsoul.co.jp
  - title: Mike del Ferro and Yasuhito Mori (afternoon concert!)
    date: 2019-05-19 15:00:00
    location: U3Chi  u3chi@yahoo.co.jp
    venue: 'Saitama, Tokyo Region (Japan)'
    url:
  - title: with Zoumana Diarra
    date: 2019-06-01 20:30:00
    location: Munganga
    venue: Amsterdam (NL)
    url: 'https://www.munganga.nl'
  - title: Mike del Ferro & Yasuhito Mori
    date: 2019-05-21 20:30:00
    location: Umeda Always
    venue: Osaka (Japan)
    url: 'http://www.always-live.info'
  - title: >-
      Lying down Concert: Mike del Ferro & Jeroen van Veen, Canto Ostinato and
      beyond
    date: 2019-11-07 20:00:00
    location: Wilminktheater
    venue: Enschede  (NL)
    url: >-
      https://www.wilminktheater.nl/programma/!/8162/jeroen-van-veen-mike-del-ferro/canto-ostinato-and-beyond-ligconcert/
  - title: Mike del Ferro and Yasuhito Mori
    date: 2019-05-20 19:00:00
    location: Tamachi Salong
    venue: Hamamatsu (Japan)
    url: 'http://08artforme.com'
  - title: Mike del Ferro and Yasuhito Mori
    date: 2019-05-23 19:00:00
    location: Jazz Flash
    venue: Niigata (Japan)
    url: 'https://r.goope.jp/jazzflash'
  - title: With André Heuvelman - Nachtgeluiden
    date: 2019-07-20 15:00:00
    location: Wonderfeel Festival
    venue: s'Graveland (NL)
    url: 'https://www.wonderfeel.nl'
  - title: >-
      Piano duo Mike del Ferro & Jeroen van Veen - Bernstein & Gershwin
      program-afternoon Concert
    date: 2019-05-26 16:30:00
    location: Grote Kerk
    venue: Edam (NL)
    url: 'http://www.piano-edam.nl/home/4'
  - title: Mike del Ferro
    date: 2019-05-22 20:00:00
    location: Request Club
    venue: Kobe-(Japan)
    url: >-
      https://www.facebook.com/photo.php?fbid=2226118000798024&set=a.208192395923938&type=3&theater
  - title: With Anders Bergcrantz and Hans de Waard
    date: 2019-08-07 20:00:00
    location: TBA
    venue: Gällivare (Sweden)
    url:
  - title: Mike del Ferro and Jeroen van Veen- Canto Ostinato and Beyond
    date: 2020-01-09 20:00:00
    location: De Meerse
    venue: Hoofddorp (NL)
    url: 'https://www.demeerse.nl/'
  - title: Mike del Ferro trio & Kwazulu Natal Heritage Choir - Mbuso Khoza
    date: 2019-06-23 20:00:00
    location: Joburg Theatre
    venue: Johannesburg (South Africa)
    url: 'https://www.joburgtheatre.com/'
  - title: Mike del Ferro trio with Sebastian Netta - Yoga Concert
    date: 2019-06-16 20:00:00
    location: TBA
    venue: Billerbeck - Münster area (Germany)
    url:
  - title: Yoga Concert with Sebastian Netta
    date: 2019-07-07 20:00:00
    location: TBA
    venue: Reelkichen (Münsterland - Germany)
    url: 'http://wuw.netta.de/project/yoga-und-achtsamkeit'
  - title: Classic meets Jazz with Maya Fridman and Sebastian Netta
    date: 2019-07-06 20:00:00
    location: Monastery
    venue: Reelkirchen (Münsterland - Germany)
    url: 'http://wuw.netta.de/project/jazz-meets-klassik'
  - title: Mike del Ferro & Yasuhito Mori
    date: 2019-05-16 19:00:00
    location: Hermit Dolphin
    venue: Hamamatsu (Japan)
    url: 'http://www3.tokai.or.jp/hermitdolphin/'
  - title: 'Classic meets Jazz, with Maya Fridman and Sebastian Netta'
    date: 2019-07-20 19:00:00
    location:
    venue: Dulmen (Münsterland) Germany
    url: 'http://wuw.netta.de/project/jazz-meets-klassik'
  - title: Yoga Concert with Maya Fridman and Sebastian Netta
    date: 2019-07-13 19:00:00
    location: Kloster Bentlage
    venue: Bentlage (Münsterland - Germany)
    url: 'http://wuw.netta.de/project/yoga-und-achtsamkeit'
  - title: With Anders Bergcrantz and Hans de Waard
    date: 2019-08-08 19:00:00
    location: TBA
    venue: Gällivare (Sweden)
    url:
  - title: with Anders Bergcrantz and Hanz de Waard
    date: 2019-08-09 19:00:00
    location: TBA
    venue: Jokkmokk (Sweden)
    url:
  - title: with Mbuso Khoza
    date: 2019-06-21 23:00:00
    location: the Chairman
    venue: Durban (South Africa)
    url: 'http://www.thechairmanlive.com/'
  - title: with Anders Bergcrantz and Hans de Waard
    date: 2019-08-10 19:00:00
    location: Seal Jazz Festival
    venue: Holmön (Sweden)
    url: >-
      https://www.facebook.com/story.php?story_fbid=2089312967783762&id=201487546566323
  - title: with Mbuso Khoza
    date: 2019-06-21 19:00:00
    location: Headroom Studio
    venue: Durban (South Africa)
    url:
  - title: with Mbuso Khoza
    date: 2019-06-28 19:00:00
    location: Alliance Francaise
    venue: Durban (South Africa)
    url:
  - title: with Phaedra Kwant
    date: 2019-06-08 21:00:00
    location: Red Light Jazz Festival
    venue: Amsterdam (NL)
    url: 'https://redlightjazz.com/'
  - title: with Wayne Escoffery
    date: 2019-06-09 16:00:00
    location: Archiduc
    venue: Brussels (Belgium)
    url: 'http://www.archiduc.net/nl'
  - title: Nachtgeluiden (Night SOunda)- with Andre Heuvelman
    date: 2019-09-06 20:00:00
    location: Open Air Theatre / Forest
    venue: Kwintelooijen (NL)
    url: 'https://www.andreheuvelman.nl'
  - title: 'infinite now-mesmerizing Visuals, with Jeoren van Veen and Andre Heuvelman'
    date: 2019-07-10 20:00:00
    location: Pernissio
    venue: Pernis (Rotterdam area)
    url: www.pernissimo.org
  - title: Canto Ostinato - Dom Tower -with Jeroen van Veen and Malgosia Fiebig
    date: 2019-08-19 20:00:00
    location: Dom Tower
    venue: Utrecht
    url: 'https://www.klokkenspelvereniging.nl/'