gigs:
  - title: 'Mike Boddé & Mike del Ferro, Mike Kwadraat'
    date: 2017-08-21 20:00:00
    location: Concertgebouw
    venue: Amsterdam
    url: www.concertgebouw.nl
  - title: with Jeroen van Veen
    date: 2017-09-28 20:00:00
    location: Breda (NL)
    venue: Orgelstorm festival
    url:
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-02 20:15:00
    location: Eindhoven (NL)
    venue: Muziekgebouw Frits Philips
    url: www.muziekgebouweindhoven.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-08 20:15:00
    location: Nijmegen (NL)
    venue: De Vereeniging
    url: www.stadsschouwburgendevereeniging.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-16 20:00:00
    location: Leeuwarden (NL)
    venue: De Harmonie
    url: www.harmonie.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-20 20:15:00
    location: Heiloo (NL)
    venue: De Beun
    url: www.theaterdebeun.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-23 20:30:00
    location: Zoetermeer (NL)
    venue: Stadstheater
    url: www.stadstheater.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-24 20:30:00
    location: Lelystad (NL)
    venue: Agora theater
    url: www.agora-lelystad.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-09 20:30:00
    location: Drachten (NL)
    venue: De Lawei
    url: www.lawei.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-16 20:15:00
    location: Laren (NL)
    venue: Singer
    url: www.singerlaren.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-23 20:15:00
    location: Woerden (NL)
    venue: Het Klooster / Theater
    url: www.kloosterwoerden.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-28 08:30:00
    location: Gouda (NL)
    venue: Goudse Schouwburg
    url: www.goudseschouwburg.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-30 20:30:00
    location: Amstelveen (NL)
    venue: Griffioen Theater
    url: www.griffioen.vu.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-31 20:30:00
    location: Heerlen (NL)
    venue: Parkstad Theater
    url: www.parkstadlimburgtheaters.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-04-04 20:15:00
    location: Delft (NL)
    venue: De Veste
    url: www.theaterdeveste.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-04-07 20:00:00
    location: Zwolle (NL)
    venue: Schouwburg Odeon
    url: www.zwolsetheaters.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-04-20 20:30:00
    location: Dordrecht (NL)
    venue: Energiehuis
    url: www.kunstmin.nl
  - title: 'Mike del Ferro with International Musicians, 12-16 September'
    date: 2017-09-12 00:00:00
    location: 'Jaffa Jazzfestival, Israel'
    venue: Israel
    url:
  - title: 'Mike del Ferro trio Japan tour, more details soon'
    date: 2017-11-24 00:00:00
    location:
    venue:
    url:
  - title: 'Mike del Ferro & Friends'
    date: 2017-09-29 20:30:00
    location: Amsterdam
    venue: Munganga theatre
    url: www.munganga.nl
  - title: Mike del Ferro trio
    date: 2018-02-18 15:00:00
    location: Vorden (NL)
    venue: Jazzclub
    url:
  - title: Duo Mike Boddé and Mike del Ferro-Mike Kwadraat
    date: 2018-03-10 20:00:00
    location: Tilburg (NL)
    venue: Paradox
    url: www.paradoxtilburg.nl
  - title: Mike del Ferro and friends
    date: 2017-09-30 20:30:00
    location: Amsterdam (NL)
    venue: Splendor
    url: www.splendoramsterdam.com
  - title: 'Duo Jeroen van Veen & Mike del Ferro'
    date: 2017-12-09 20:00:00
    location: Amsterdam
    venue: Ostade Theater
    url:
  - title: 'Mike del Ferro & Jeroen van Veen'
    date: 2017-11-16 20:00:00
    location: Amsterdam
    venue: Roode Bioscoop
    url: www.roodebioscoop.nl
  - title: 'Mike del Ferro & Mike Boddé'
    date: 2017-11-17 20:00:00
    location: Amsterdam
    venue: Roode Bioscoop
    url: www.roodebioscoop.nl
  - title: 'Mike del Ferro & Remy van Kesteren'
    date: 2017-11-18 20:00:00
    location: Amsterdam
    venue: Roode Bioscoop
    url: www.roodebioscoop.nl
  - title: 'Mike del Ferro, solo'
    date: 2017-09-03 16:00:00
    location: Amstelveen
    venue: TBA
    url:
  - title: 'South Africa, Masterclasses, Concerts and Recordings, more details soon'
    date: 2017-12-13 00:00:00
    location:
    venue:
    url: