gigs:
  - title: 'Mike del Ferro, Tony Lakatos, Sebastian Netta and Uli Wentzlaff'
    date: 2018-06-03 16:00:00
    location: TBA
    venue: Münster (Germany)
    url:
  - title: 'Summer evening up in the Dom tower, Utrecht'
    date: 2018-08-20 20:00:00
    location: Domtoren
    venue: Utrecht (NL)
    url: 'http://www.klokkenspelvereniging.nl'
  - title: Harp festival with Sitar Master Niladri Kumar
    date: 2018-05-13 16:00:00
    location: Tivoli Vredenburg
    venue: Utrecht
    url: 'http://harpfestival.nl/nl/'
  - title: Mike Boddé & Mike del Ferro
    date: 2018-12-21 20:00:00
    location: Lantaren Venster
    venue: Rotterdam (NL)
    url: 'http://www.lantarenvenster.nl'
  - title: 'Jazz meets Bernstein, Mike del Ferro trio with Deborah Carter'
    date: 2018-07-01 16:00:00
    location: TBA
    venue: Bishkek (Kyrgistan)
    url:
  - title: Solo performance at Pianists evening in Amsterdam
    date: 2018-06-06 20:00:00
    location: Splendor
    venue: Amsterdam  (NL)
    url: 'http://www.splendoramsterdam.com'
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-05-08 20:30:00
    location: Griffioen Theater
    venue: Amstelveen
    url: 'http://www.griffioen.vu.nl'
  - title: Mike del Ferro Solo Concert
    date: 2018-05-19 20:00:00
    location: Munganga
    venue: Amsterdam (NL)
    url: 'http://www.munganga.nl'
  - title: Mike del Ferro & Svenja Staats
    date: 2018-06-10 15:00:00
    location: Ambassador hotel
    venue: Amsterdam
    url:
  - title: Jazz meets Bernstein
    date: 2018-07-24 20:00:00
    location: Albania Jazz festival
    venue: Tirana
    url:
  - title: Mike del Ferro & Mike Boddé - Mike Kwadraat
    date: 2018-11-17 20:30:00
    location: Porgy & Bess
    venue: Terneuzen (NL)
    url: 'http://www.porgyenbess.nl'
  - title: Mike del Ferro-Jazz meets Bernstein
    date: 2018-07-28 20:00:00
    location: TBA
    venue: Tirana (Albania)
    url: