gigs:
  - title: Mike del Ferro solo and with Leslie Christopher (Concert at 5PM!)
    date: 2019-03-02 17:00:00
    location: 'Ken Gregory Studios, 800 East Ave Northeast, Atlanta, GA 30312-1412'
    venue: Atlanta (USA)
    url: 'https://app.eventsframe.com/e/m39GQuHiE/mike-del-ferro-live/'
  - title: Holland Americas Group
    date: 2019-03-10 17:00:00
    location: Le Poisson Rouge
    venue: New York City (US)
    url: >-
      https://lpr.com/lpr_events/holland-americas-group-march-10-2019/?fbclid=IwAR2aZ_JvuaiGPU5yBcsPoO8Wj4gpru3onaUU1wL3h4It25RKbOBWQtAtCDE
  - title: Mike del Ferro trio with Sebastiaan Kaptein and Yasuhito Mori
    date: 2019-05-24 20:00:00
    location: Body and Soul
    venue: Tokyo- Japan
    url: www.bodyandsoul.co.jp
  - title: with Zoumana Diarra
    date: 2019-06-01 20:30:00
    location: Munganga
    venue: Amsterdam (NL)
    url: 'https://www.munganga.nl'
  - title: Holland Americas Group
    date: 2019-03-08 20:00:00
    location: ShapeShifter Lab
    venue: New York City (USA)
    url: 'https://shapeshifterlab.com/'
  - title: Mike del Ferro trio
    date: 2019-03-03 20:30:00
    location: Velvet Note
    venue: Atlanta (USA)
    url: 'https://thevelvetnote.com/'
  - title: 'The Infinite now, Mesmerizing Visuals with Live Music'
    date: 2019-04-11 20:00:00
    location: Pernissimo
    venue: Pernis (NL)
    url: www.pernissimo.org
  - title: 'Mike del Ferro 4tet with Ricardo Pinheiro, Massimo Cavalli and Joel Silva'
    date: 2019-03-23 20:00:00
    location: Hot Clube
    venue: Lisbon (Portugal)
    url: 'https://www.hcp.pt'
  - title: Holland Americas Group with Andre Heuvelman and Santiago Cimadevilla
    date: 2019-03-10 11:00:00
    location: Le poisson Rouge
    venue: New York City (US)
    url: 'https://www.lpr.com'
  - title: Holland Americas Group with Andre Heuvelman and Santiago Cimadevilla
    date: 2019-03-08 18:00:00
    location: Areté Venue & Gallery
    venue: New York (USA)
    url: 'https://www.aretevenue.com'
  - title: 'Mike del Ferro 4tet with Ricardo Pinheiro, Massimo Cavalli and Joel Silva'
    date: 2019-03-22 20:00:00
    location: Hot Clube
    venue: Lissabon (Portugal)
    url: 'https://www.hcp.pt'
  - title: With Maya Fridman and Sebastian Netta (afternoon)
    date: 2019-04-14 15:00:00
    location: TBA
    venue: Münster (Germany)
    url:
  - title: 'Duo with Josee Koning, Brazilian Songs (Afternoon Concert!)'
    date: 2019-02-17 20:00:00
    location: Gelderlandfabriek
    venue: Culemborg (NL)
    url: >-
      https://www.degelderlandfabriek.nl/events/event/muziek-jam-jazz-pizza-josee-koning-mike-del-ferro/
  - title: Clinic "selfmanagement and networking for musicians"
    date: 2019-03-11 18:00:00
    location: Berklee
    venue: Boston (USA)
    url: 'https://bostonconservatory.berklee.edu'
  - title: Mike del Ferro Solo recital (at Noon!)
    date: 2019-03-13 12:00:00
    location: Lafayette College
    venue: Easton (USA)
    url: 'https://www.lafayette.edu/'
  - title: 'Mike del Ferro trio with Bram Wijnands (bass), Pat Adams (Drums)'
    date: 2019-03-14 20:00:00
    location: Kansas City Bier Company
    venue: Kansas City (USA)
    url: 'https://kcbier.com'
  - title: >-
      Mike del Ferro trio with Bram Wijnands (bass), Pat Adams (Drums) & Bobby
      Watson
    date: 2019-03-15 20:00:00
    location: The Majestic
    venue: Kansas City (USA)
    url: 'http://majestickc.com/upcoming-shows/'
  - title: >-
      Mike del Ferro trio with Bram Wijnands (bass), Pat Adams (Drums) & Bobby
      Watson
    date: 2019-03-16 20:00:00
    location: The Majestic
    venue: Kansas City (USA
    url: 'http://majestickc.com/upcoming-shows/'
  - title: with Andre Heuvelman and Trajecti Voices Choir
    date: 2019-04-06 20:00:00
    location: Church
    venue: Diepenveen (NL)
    url: 'https://www.trajectivoces.net'
  - title: with Andre Heuvelman and Trajecti Voices Choir (afternoon concert!)
    date: 2019-04-07 16:00:00
    location: Catharina Church
    venue: Utrecht (NL)
    url: 'https://www.trajectivoces.net'
  - title: with daughter Ella del Ferro and her band
    date: 2019-04-08 20:00:00
    location: Melkweg
    venue: Amsterdam (NL)
    url: 'https://www.melkweg.nl'