gigs:
  - title: Yoga & Soundscapes in the early morning 7am!! With André Heuvelman
    date: 2018-10-21 07:00:00
    location:
    venue: Rotterdam (NL)
    url: >-
      http://www.rotterdamsphilharmonisch.nl/nl/concerten/andré-heuvelman-yoga-soundscapes
  - title: 'Tour Japan, May 2019, more details soon'
    date: 2019-05-12 20:00:00
    location:
    venue: Japan
    url:
  - title: Mike del Ferro trio & David Linx
    date: 2018-12-15 20:30:00
    location: Splendor
    venue: Amsterdam (NL)
    url: 'https://www.splendoramsterdam.com'
  - title: Masterclass
    date: 2018-11-14 15:00:00
    location: Jazz Schule
    venue: Basel (CH)
    url:
  - title: Mike del Ferro & Mike Boddé & Mystery Guest
    date: 2018-10-13 20:00:00
    location: Pianoduo festival - Amstelkerk
    venue: Amsterdam (NL)
    url: 'https://www.pianoduofestival.nl'
  - title: Mike del Ferro & Mike Boddé - Mike Kwadraat
    date: 2018-11-17 20:30:00
    location: Porgy & Bess
    venue: Terneuzen (NL)
    url: 'http://www.porgyenbess.nl'
  - title: 'Mike del Ferro, Rogerio Boccato, Hermine Deurloo, Joris Teepe'
    date: 2018-10-30 20:00:00
    location: De Oosterpoort
    venue: Groningen (NL)
    url: >-
      https://www.de-oosterpoort.nl/programma/joris-teepe-presents-nyctg-rogerio-boccato-30-oktober/
  - title: 'Mike Boddé & Mike del Ferro, Mike Kwadraat'
    date: 2018-12-21 20:00:00
    location: Lantaren Venster
    venue: Rotterdam (NL)
    url: 'https://www.lantarenvenster.nl/programma/mike-kwadraat/'
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-11 20:00:00
    location: Meervaart
    venue: Amsterdam (NL)
    url:
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-03 20:00:00
    location: De Flint
    venue: Amersfoort (NL
    url:
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-04 20:00:00
    location: De Vereeniging
    venue: Nijmegen (NL)
    url:
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-05 20:00:00
    location: Theater
    venue: Hoorn (NL)
    url:
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-09 20:00:00
    location: Nieuwe Luxor
    venue: Rotterdam (NL)
    url:
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-10 20:00:00
    location: Theater
    venue: Enschede (NL)
    url:
  - title: 'Tour Norway, more details soon'
    date: 2019-05-04 20:00:00
    location: Norway
    venue:
    url:
  - title: 'Mike del Ferro & Mike Boddé , Mike Kwadraat'
    date: 2018-11-28 20:00:00
    location: Pianino
    venue: Den Haag (NL)
    url: 'https://www.facebook.com/pianinotheater/'
  - title: 'Mike del Ferro & Mike Boddé,, Mike Kwadraat'
    date: 2018-11-16 20:00:00
    location: Tivoli Vredenburg
    venue: Utrecht
    url: 'https://www.tivolivredenburg.nl/agenda/mike-kwadraat-16-11-2018/'
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-11-20 22:00:00
    location: The Tower
    venue: Zutphen (NL)
    url: 'https://www.facebook.com/jazzatthetower/'
  - title: with Michael Moore
    date: 2018-12-01 20:00:00
    location: Splendor
    venue: Amsterdam
    url: www.splendoramsterdam.com
  - title: 'with Jeroen van Veen, Canto Ostinato and beyond'
    date: 2019-02-09 20:00:00
    location: Pernissimo
    venue: Pernis (NL)
    url: www.pernissimo.org
  - title: Mike del Ferro trio  & David Linx
    date: 2018-12-05 20:00:00
    location: De Observant
    venue: Amersfoort
    url: www.deobservant.nl
  - title: Mike del Ferro trio and David Linx Concert at 1PM!)
    date: 2018-12-09 13:00:00
    location: Beauforthuis
    venue: Austerlitz
    url: www.beauforthuis.nl
  - title: Mike del Ferro tba
    date: 2019-03-22 13:00:00
    location: Hot Clube
    venue: Lissabon (Portugal)
    url:
  - title: 'Tour USA , more details soon'
    date: 2019-03-04 13:00:00
    location: USA
    venue:
    url: