gigs:
  - title: 'Mike del Ferro & Claron McFadden'
    date: 2017-05-20 08:00:00
    location: Tindall Villa
    venue: Bussum (NL)
    url: 'http://www.tindal.nl/Tindal/20170520.html'
  - title: 'Mike Boddé & Mike del Ferro, Mike Kwadraat'
    date: 2017-08-21 08:00:00
    location: Concertgebouw
    venue: Amsterdam
    url: www.concertgebouw.nl
  - title: 'Jeroen van Veen & Mike del Ferro piano duo'
    date: 2017-05-26 20:00:00
    location: Pianino theater ( in the Moof building)
    venue: Den Haag
    url: 'https://www.facebook.com/pianinotheater/?ref=ts&fref=ts'
  - title: Mike del Ferro trio
    date: 2017-07-15 20:00:00
    location: 'Krakow Jazzfestival, Poland'
    venue: Krakow
    url:
  - title: 'Duo Jeroen van Veen & Mike del Ferro (morning concert!)'
    date: 2017-07-30 11:30:00
    location: Kasteeltuin Middachten
    venue: Rheden (NL)
    url: 'http://www.middachten.nl/zomerconcerten-in-de-tuin/'
  - title: with Jeroen van Veen
    date: 2017-09-29 20:00:00
    location: Breda
    venue: Orgelstorm festival
    url:
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-02 20:00:00
    location: Eindhoven
    venue: Muziekgebouw
    url:
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-08 20:00:00
    location: 'Nijmegen,'
    venue: De Vereeniging
    url:
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-16 20:00:00
    location: 'Leeuwarden, more details will follow'
    venue:
    url:
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-20 20:00:00
    location: 'Heiloo, more details will follow'
    venue:
    url:
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-23 20:00:00
    location: 'Zoetermeer, more details will follow'
    venue:
    url:
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-24 20:00:00
    location: 'Lelystad, more details will follow'
    venue:
    url:
  - title: Canto Ostinato meets Jazz with Jeroen van Veen and friends
    date: 2017-06-16 08:00:00
    location: Amsterdam
    venue: Tenclub
    url:
  - title: Mike del Ferro trio
    date: 2017-07-14 20:00:00
    location: 'Krakow, Poland'
    venue: International Jazz festival
    url:
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-28 08:00:00
    location: Gouda (NL)
    venue: De Goudse Schouwburg
    url: 'https://www.goudseschouwburg.nl/voorstellingen/2710/Mike_Kwadraat/Mike_Bodde_Mike_Del_Ferro/'
  - title: Guest with Fabiano Chagas
    date: 2017-05-05 20:00:00
    location: Amsterdam (NL)
    venue: Munganga theater
    url: 'https://munganga.nl/mini2/programma/3815'