gigs:
  - title: 'Mike del Ferro, Tony Lakatos, Sebastian Netta and Uli Wentzlaff'
    date: 2018-06-03 16:00:00
    location: muensterland studios.
    venue: Münster (Germany)
    url: 'http://www.muensterlandstudios.de'
  - title: 'Summer evening up in the Dom tower, Utrecht with the music of Sting'
    date: 2018-08-20 20:00:00
    location: Domtoren
    venue: Utrecht (NL)
    url: 'http://www.klokkenspelvereniging.nl'
  - title: 'Canto Ostinato meets Jazz, Mike del Ferro & Jeroen van Veen'
    date: 2018-06-09 20:00:00
    location: Tenclub
    venue: Amsterdam
    url: 'https://www.facebook.com/events/1479100408868491/'
  - title: Mike Boddé & Mike del Ferro
    date: 2018-12-21 20:00:00
    location: Lantaren Venster
    venue: Rotterdam (NL)
    url: 'http://www.lantarenvenster.nl'
  - title: 'Jazz meets Bernstein, Mike del Ferro trio with Deborah Carter'
    date: 2018-07-01 16:00:00
    location: TBA
    venue: Bishkek (Kyrgistan)
    url:
  - title: Solo performance at Pianists evening in Amsterdam
    date: 2018-06-06 20:00:00
    location: Splendor
    venue: Amsterdam  (NL)
    url: 'http://www.splendoramsterdam.com'
  - title: Mike del Ferro trio
    date: 2018-06-16 15:30:00
    location: Eef festival
    venue: Goes (NL)
    url:
  - title: Mike del Ferro wit members of the Rotterdam Philharmonic
    date: 2018-06-21 20:00:00
    location: Dutch Embassy
    venue: Paris (F)
    url:
  - title: Mike del Ferro & Svenja Staats
    date: 2018-06-10 16:00:00
    location: Ambassador hotel
    venue: Amsterdam
    url: 'https://m.facebook.com/literairesalon/?locale2=nl_NL'
  - title: Mike del Ferro
    date: 2018-07-24 20:00:00
    location: Albania Jazz festival
    venue: Tirana (Albania)
    url:
  - title: Mike del Ferro & Mike Boddé - Mike Kwadraat
    date: 2018-11-17 20:30:00
    location: Porgy & Bess
    venue: Terneuzen (NL)
    url: 'http://www.porgyenbess.nl'
  - title: Mike del Ferro-
    date: 2018-07-28 20:00:00
    location: TBA
    venue: Tirana (Albania)
    url: