gigs:
  - title: 'Mike del Ferro & Pekka Pylkannen'
    date: 2016-10-29 20:00:00
    location: Birdseye
    venue: Basel (CH)
    url: www.birdseye.ch
  - title: 'Mike del Ferro trio & Claron McFadden'
    date: 2017-01-06 20:00:00
    location: De Toonzaal
    venue: Den Bosch (NL)
    url: www.detoonzaal.nl
  - title: 'Mike del Ferro & Pekka Pylkannen'
    date: 2016-10-28 20:00:00
    location: Birds Eye
    venue: Basel (CH)
    url: www.birdseye.ch
  - title: Mike del Ferro trio
    date: 2017-01-14 20:00:00
    location: 10/14 Club
    venue: Warszaw-Poland
    url:
  - title: Mike del Ferro trio
    date: 2017-01-17 19:30:00
    location: NOSPR
    venue: Katowice-Poland
    url: 'http://www.nospr.org.pl/en/concerts/627/wtorkowy-klub-jazzowy-mike-del-ferro-trio-feat-ceumar'
  - title: Mike del Ferro / Mike Boddé pianoduo
    date: 2017-02-10 20:30:00
    location: De Doelen
    venue: Rotterdam-NL
    url: www.dedoelen.nl
  - title: Mike del Ferro / Claron McFadden - opera meets jazz
    date: 2017-01-07 20:00:00
    location: Splendor
    venue: Amsterdam
    url: www.splendoramsterdam.com
  - title: 'Mike del Ferro & Claron McFadden'
    date: 2016-11-04 20:00:00
    location: De Morgenster
    venue: Hilversum (NL)
    url: 'http://www.seinconcerten.nl/'
  - title: Mike del Ferro
    date: 2016-12-10 20:30:00
    location: TBA
    venue: Antwerp (B)
    url:
  - title: 'Mike del Ferro & Claron McFadden'
    date: 2016-11-05 20:00:00
    location: Tenclub
    venue: Amsterdam (NL)
    url:
  - title: Mike del Ferro- solo recital
    date: 2016-11-03 20:30:00
    location: Splendor
    venue: Amsterdam (NL)
    url: www.splendoramsterdam.com
  - title: Mike del Ferro trio
    date: 2016-11-01 22:00:00
    location: Luxor theater
    venue: Zuthpen (NL)
    url:
  - title: Mike del Ferro trio
    date: 2016-12-11 22:00:00
    location: Jazzclub
    venue: Vorden (NL)
    url:
  - title: 'Mike del Ferro & Claron McFadden'
    date: 2016-11-20 14:30:00
    location: De Roode bioscoop
    venue: Amsterdam (NL)
    url: 'http://www.roodebioscoop.nl/Roode-Zondagen/467-CLARON-MCFADDEN-en-MIKE-DEL-FERRO/1338'
  - title: Duo Mike Boddé and Mike del Ferro (Mike Kwadraat)
    date: 2016-11-22 19:00:00
    location: Pianino Theater
    venue: Den Haag (NL)
    url: 'http://www.pianinotheater.nl/styled-10/concerten.html'
  - title: Duo with Leoni Jansen
    date: 2016-12-17 20:00:00
    location: Brocope Theater
    venue: Oldeberkoop (Friesland/NL)
    url:
  - title: Mike del Ferro trio with Niladri Kumar and Deborah Carter
    date: 2017-01-09 19:00:00
    location: TBA
    venue: Sharja (Dubai)
    url:
  - title: 'Tour Sweden, jan 31-feb 8 more details soon'
    date: 2017-01-31 15:00:00
    location: Sweden
    venue:
    url:
  - title: Mike del Ferro trio
    date: 2017-03-12 15:00:00
    location: Jazzclub
    venue: Valkenswaard (NL)
    url: