gigs:
  - title: Mike del Ferro solo recital
    date: 2018-09-24 19:00:00
    location: Rene van Beeck's stage
    venue: Amsterdam (NL)
    url: >-
      https://www.facebook.com/René-van-Beeck-pianos-vleugels-podium-229411223771915/?timeline_context_item_type=intro_card_work&timeline_context_item_source=1092073354&fref=tag
  - title: Mike Boddé & Mike del Ferro
    date: 2018-12-21 20:00:00
    location: Lantaren Venster
    venue: Rotterdam (NL)
    url: 'http://www.lantarenvenster.nl'
  - title: Mike del Ferro trio & David Linx
    date: 2018-12-15 20:30:00
    location: Splendor
    venue: Amsterdam (NL)
    url: 'https://www.splendoramsterdam.com'
  - title: Masterclass
    date: 2018-11-14 10:00:00
    location: Jazz Schule
    venue: Basel (CH)
    url:
  - title: Mike del Ferro & Kim Hoorweg
    date: 2018-07-25 20:00:00
    location: Albania Jazz festival
    venue: Tirana (Albania)
    url:
  - title: Mike del Ferro & Mike Boddé - Mike Kwadraat
    date: 2018-11-17 20:30:00
    location: Porgy & Bess
    venue: Terneuzen (NL)
    url: 'http://www.porgyenbess.nl'
  - title: Mike del Ferro. Masterclass
    date: 2018-07-28 20:00:00
    location: TBA
    venue: Tirana (Albania)
    url:
  - title: 'Mike Boddé & Mike del Ferro, Mike Kwadraat'
    date: 2018-12-21 20:00:00
    location: Lantaren Venster
    venue: Rotterdam (NL)
    url: 'https://www.lantarenvenster.nl/programma/mike-kwadraat/'
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-11 20:00:00
    location: Meervaart
    venue: Amsterdam (NL)
    url:
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-03 20:00:00
    location: De Flint
    venue: Amersfoort (NL
    url:
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-04 20:00:00
    location: De Vereeniging
    venue: Nijmegen (NL)
    url:
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-05 20:00:00
    location: Theater
    venue: Hoorn (NL)
    url:
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-09 20:00:00
    location: Nieuwe Luxor
    venue: Rotterdam (NL)
    url:
  - title: >-
      Opera meets Jazz! With members of the Metropole orchestra & Claron
      McFadden
    date: 2019-01-10 20:00:00
    location: Theater
    venue: Enschede (NL)
    url: