gigs:
  - title: 'Duo Claron McFadden& Mike del Ferro.'
    date: 2016-08-12T20:00:00.000Z
    location: Radar beyond music festival
    venue: 'Varna, Bulgaria'
    url:
  - title: Mike del Ferro / Jeroen van Veen/ Malgosia Fiebig
    date: 2016-08-22T20:00:00.000Z
    location: Dom Tower
    venue: Utrecht (NL)
    url:
  - title: 'Mike del Ferro & Pekka Pylkannen'
    date: 2016-10-29T20:00:00.000Z
    location: Birdseye
    venue: Basel (CH)
    url: www.birdseye.ch
  - title: 'Mike del Ferro trio & Claron McFadden'
    date: 2017-01-06T20:00:00.000Z
    location: De Toonzaal
    venue: Den Bosch (NL)
    url: www.detoonzaal.nl
  - title: 'Mike del Ferro & Pekka Pylkannen'
    date: 2016-10-28T20:00:00.000Z
    location: Birds Eye
    venue: Basel (CH)
    url: www.birdseye.ch
  - title: '"networking and selfmanagement for musicians"'
    date: 2016-10-26T14:30:00.000Z
    location: Jazzschule
    venue: Basel-Switserland
    url:
  - title: Mike del Ferro trio
    date: 2017-01-14T20:00:00.000Z
    location: 10/14 Club
    venue: Warszaw-Poland
    url:
  - title: Mike del Ferro trio
    date: 2017-01-17T20:00:00.000Z
    location: TBA
    venue: Katowice-Poland
    url:
  - title: Mike del Ferro / Mike Boddé pianoduo
    date: 2017-02-10T20:30:00.000Z
    location: De Doelen
    venue: Rotterdam-NL
    url: www.dedoelen.nl
  - title: Mike del Ferro / Claron McFadden - opera meets jazz
    date: 2017-01-07T20:00:00.000Z
    location: Splendor
    venue: Amsterdam
    url: www.splendoramsterdam.com
  - title: 'Mike del Ferro & Claron McFadden'
    date: 2016-11-04T20:00:00.000Z
    location: De Morgenster
    venue: Hilversum (NL)
    url: 'http://www.seinconcerten.nl/'
  - title: 'Mike del Ferro, Mola Sylla, Pernell Saturnino and Christian Galvez'
    date: 2016-08-01T19:00:00.000Z
    location: Flores Festival- Parque Cultural Nocturno
    venue: 'Medellin, Colombia'
    url:
  - title: Mike del Ferro trio feat. Christian Galvez y Alejandro Espinosa
    date: 2016-08-03T20:00:00.000Z
    location: 'Universidad Central, Aula Magna'
    venue: Santiago de Chile
    url:
  - title: 'Who is the Bossa (with José Koning, Nelson faria and Daniel Pezzoti)'
    date: 2016-10-21T20:00:00.000Z
    location: Ruïnekerk
    venue: Bergen (NL)
    url:
  - title: 'Who is the Bossa (with José Koning, Nelson faria and Daniel Pezzoti)'
    date: 2016-10-22T20:00:00.000Z
    location: 'Porgy & Bess'
    venue: Terneuzen (NL)
    url:
  - title: 'Solo recital, pianowandeling Culemborg'
    date: 2016-09-11T13:30:00.000Z
    location: tba
    venue: Culemborg (NL)
    url:
  - title: Mike del Ferro trio
    date: 2016-07-22T20:00:00.000Z
    location: 'B&L PIANO PUB CR. 4A # 66-03'
    venue: 'Bogota, Colombia'
    url:
  - title: Mike del Ferro trio
    date: 2016-07-23T21:30:00.000Z
    location: 'MATIK-MATIK CR. 11 # 67-20 9:30 PM $10.000'
    venue: 'Bogota, Colombia'
    url:
  - title: Mike del Ferro trio
    date: 2016-07-28T20:00:00.000Z
    location: la Pascasia
    venue: Medellin (Colombia)
    url:
  - title: Mike del Ferro- solo recital
    date: 2016-11-03T20:30:00.000Z
    location: Splendor
    venue: Amsterdam (NL)
    url: www.splendoramsterdam.com