gigs:
  - title: 'Mike del Ferro, solo recital'
    date: 2016-03-29T18:00:00.000Z
    location: Teatro Universario Camilo Torres restrepo
    venue: Medellin-Colombia
    url: ''
  - title: 'Mike del Ferro, masterclass'
    date: 2016-03-29T09:00:00.000Z
    location: EAFIT
    venue: Medellin-Colombia
    url: ''
  - title: Mike del Ferro trio
    date: 2016-03-30T20:00:00.000Z
    location: Zorba
    venue: Medellin-Colombia
    url: ''
  - title: 'Mike del Ferro trio, lecture and concert'
    date: 2016-04-02T16:00:00.000Z
    location: Edificio Lugo (calle 6)
    venue: Medellin-Colombia
    url: ''
  - title: Mike del Ferro / Lupa Santiago
    date: 2016-04-07T21:00:00.000Z
    location: Jazz B
    venue: Sao Paulo-Brazil
    url: 'https://www.facebook.com/club.JazzB/photos/gm.1665884860344064/1081078078610514/?type=3&theater'
  - title: Mike del Ferro and Mike Boddé pianoduo/video artist Mirthe Dokter
    date: 2016-04-15T20:00:00.000Z
    location: De Kleine Komedie
    venue: Amsterdam (NL)
    url: 'http://www.dekleinekomedie.nl'
  - title: Mike del Ferro and Mike Boddé pianoduo/video artist Mirthe Dokter
    date: 2016-04-16T20:00:00.000Z
    location: De Kleine Komedie
    venue: Amsterdam (NL)
    url: 'http://www.dekleinekomedie.nl'
  - title: Kuwait Jazz festival
    date: 2016-04-28T20:00:00.000Z
    location: TBA
    venue: Kuwait
    url: ''
  - title: Mike del Ferro with the Metropole orchestra
    date: 2016-05-08T11:00:00.000Z
    location: 'Concertgebouw, main hall ( 11am! )'
    venue: Amsterdam (NL)
    url: 'http://www.concertgebouw.nl'
  - title: 'Mike del Ferro trio & Claron McFadden'
    date: 2016-05-13T20:00:00.000Z
    location: Beauforthuis
    venue: Austerlitz (Zeist/NL)
    url: 'http://www.beauforthuis.nl'
  - title: 'Mike del Ferro / Claron McFadden, stings and horns Metropole'
    date: 2016-06-09T20:00:00.000Z
    location: Scheldetheater
    venue: Terneuzen (NL)
    url: ''
  - title: The music of Queen Mike del Ferro / Jeroen van Veen/ Malgosia Fiebig
    date: 2016-06-11T20:00:00.000Z
    location: Cathedral
    venue: Brugge (Belgium)
    url: ''
  - title: Mike del Ferro / Jeroen van Veen/ Malgosia Fiebig
    date: 2016-08-22T20:00:00.000Z
    location: Dom Tower
    venue: Utrecht (NL)
    url: ''
  - title: 'Mike del Ferro & Pekka Pylkannen'
    date: 2016-10-29T20:00:00.000Z
    location: Birdseye
    venue: Basel (CH)
    url: www.birdseye.ch
  - title: 'Mike del Ferro trio & Claron McFadden'
    date: 2017-01-06T20:00:00.000Z
    location: De Toonzaal
    venue: Den Bosch (NL)
    url: www.detoonzaal.nl
  - title: Masterclass
    date: 2016-04-07T15:00:00.000Z
    location: Souza Lima
    venue: Sao Paulo-Brazil
    url: 'https://www.facebook.com/events/100309520364785/'
  - title: "Mike del Ferro / Lupa Santiago 5'"
    date: 2016-04-06T21:00:00.000Z
    location: Madeleine
    venue: Sao Paulo-Brazil
    url: 'R. Aspicuelta, 201 - Vila Madalena, São Paulo'
  - title: 'Mike del Ferro & Pekka Pylkannen'
    date: 2016-10-28T20:00:00.000Z
    location: Birds Eye
    venue: Basel (CH)
    url: www.birdseye.ch
  - title: "Mike del Ferro / Lupa Santiago 5'"
    date: 2016-04-08T20:00:00.000Z
    location: Casa do Musica
    venue: Avare-Sao Paulo-Brazil
    url: ''
  - title: '"networking and selfmanagement for musicians"'
    date: 2016-10-27T15:00:00.000Z
    location: Jazzschule
    venue: Basel-Switserland
    url: ''
  - title: Mike del Ferro - live TV Podium Witteman
    date: 2016-04-10T18:00:00.000Z
    location: ''
    venue: Dutch National Television
    url: ''
  - title: Canto Ostinato meets Jazz (with Jeroen and Sandra van Veen)
    date: 2016-06-18T20:00:00.000Z
    location: TBA
    venue: Shikodra-Albania
    url: ''
  - title: 'Mike del Ferro trio & orchestra'
    date: 2016-05-27T20:00:00.000Z
    location: Concert hall of National Radio
    venue: Kiev (Ukraine)
    url: ''
  - title: Canto Ostinato for 10 pianists at Festival Classique
    date: 2016-06-12T16:00:00.000Z
    location: tba
    venue: The Hague (NL)
    url: ''
  - title: Canto Ostinato meets Jazz (with Jeroen and Sandra van Veen)
    date: 2016-06-17T20:00:00.000Z
    location: Opera House
    venue: Tirana (Albania)
    url: ''
  - title: Solo recital
    date: 2016-03-29T20:00:00.000Z
    location: Universidad de Antioquia
    venue: Medellin (Colombia)
    url: ''
  - title: Mike del Ferro trio
    date: 2017-01-14T20:00:00.000Z
    location: 10/14 Club
    venue: Warszaw-Poland
    url: ''
  - title: Mike del Ferro trio
    date: 2017-01-17T20:00:00.000Z
    location: TBA
    venue: Katowice-Poland
    url: ''
  - title: Mike del Ferro / Mike Boddé pianoduo
    date: 2017-02-10T20:30:00.000Z
    location: De Doelen
    venue: Rotterdam-NL
    url: www.dedoelen.nl