gigs:
  - title: 'Mike del Ferro , Solo Recital'
    date: 2019-05-17 19:00:00
    location: Kiyora Hall
    venue: 'Minamioguni , Kyushu, (Japan)'
    url:
  - title: Mike del Ferro- Solo recital
    date: 2019-05-18 19:00:00
    location: City Hall
    venue: Hirado (Japan)
    url:
  - title: Mike del Ferro and Yasuhito Mori
    date: 2019-05-24 20:00:00
    location: Body and Soul
    venue: Tokyo- Japan
    url: www.bodyandsoul.co.jp
  - title: Mike del Ferro and Yasuhito Mori
    date: 2019-05-19 19:00:00
    location: U3Chi
    venue: 'Saitama, Tokyo Region (Japan)'
    url:
  - title: with Zoumana Diarra
    date: 2019-06-01 20:30:00
    location: Munganga
    venue: Amsterdam (NL)
    url: 'https://www.munganga.nl'
  - title: Mike del Ferro & Yasuhito Mori
    date: 2019-05-21 20:30:00
    location: Umeda Always
    venue: Osaka (Japan)
    url: 'http://www.always-live.info'
  - title: 'The Infinite now, Mesmerizing Visuals with Live Music'
    date: 2019-04-11 20:00:00
    location: Pernissimo
    venue: Pernis (NL)
    url: www.pernissimo.org
  - title: Mike del Ferro and Yasuhito Mori
    date: 2019-05-20 19:00:00
    location: Tamachi Salong
    venue: Hamamatsu (Japan)
    url: 'http://08artforme.com'
  - title: Mike del Ferro and Yasuhito Mori
    date: 2019-05-23 19:00:00
    location: Jazz Flash
    venue: Niigata (Japan)
    url: 'https://r.goope.jp/jazzflash'
  - title: With Maya Fridman and Sebastian Netta (afternoon)
    date: 2019-04-14 15:00:00
    location: TBA
    venue: Münster (Germany)
    url:
  - title: >-
      Piano duo Mike del Ferro & Jeroen van Veen - Gershwin program-afternoon
      Concert
    date: 2019-05-26 16:30:00
    location: Grote Kerk
    venue: Edam (NL)
    url: 'http://www.piano-edam.nl/home/4'
  - title: Mike del Ferro
    date: 2019-05-22 20:00:00
    location: TBA
    venue: Kobe-(Japan)
    url:
  - title: The Infinite now- Water Conference morning concert
    date: 2019-04-13 09:00:00
    location: Tolhuistuin
    venue: Amsterdam (NL)
    url: 'https://www.rotary.nl/d1580/activiteiten/discon/programma/'
  - title: Mike del Ferro and Jeroen van Veen- Canto Ostinato and Beyond
    date: 2020-01-09 20:00:00
    location: De Meerse
    venue: Hoofddorp (NL)
    url: 'https://www.demeerse.nl/'
  - title: Mike del Ferro trio & Kwazulu Natal Heritage Choir - Mbuso Khoza
    date: 2019-06-23 20:00:00
    location: TBA
    venue: Johannesburg (South Africa)
    url:
  - title: Mike del Ferro trio with Sebastian Netta - Yoga Concert
    date: 2019-06-16 20:00:00
    location: TBA
    venue: Billerbeck - Münster area (Germany)
    url:
  - title: with Andre Heuvelman and Trajecti Voices Choir
    date: 2019-04-06 20:00:00
    location: Church
    venue: Diepenveen (NL)
    url: 'https://www.trajectivoces.net'
  - title: with Andre Heuvelman and Trajecti Voices Choir (afternoon concert!)
    date: 2019-04-07 16:00:00
    location: Catharina Church
    venue: Utrecht (NL)
    url: 'https://www.trajectivoces.net'
  - title: with daughter Ella del Ferro and her band
    date: 2019-04-08 20:00:00
    location: Melkweg
    venue: Amsterdam (NL)
    url: 'https://www.melkweg.nl'