gigs:
  - title: Mike del Ferro / Palle Danielson / Anders Kjellberg
    date: 2016-02-12T19:00:00.000Z
    location: 'Gothenburg, SE'
    venue: Jazz Club Nefertiti
    url: 'http://www.nefertiti.se/arrangemang/del-ferro-danielsson-kjellberg-2016/'
  - title: 'Lecture: "selfmanagement and networking for musicians"'
    date: 2016-02-18T19:15:00.000Z
    location: Tilburg (NL)
    venue: Fontys Hogeschool
    url: ''
  - title: 'Mike del Ferro and the Brasilia Symphony orchestra,'
    date: 2016-03-08T19:00:00.000Z
    location: Brasilia (B)
    venue: Cine Brasilia
    url: 'https://www.facebook.com/CineBrasilia1960/'
  - title: Mike del Ferro
    date: 2016-03-10T20:00:00.000Z
    location: Ceilândia (Brasil)
    venue: SESC-Teatro Newton Rossi
    url: ''
  - title: Mike del Ferro trio with Marcio Bahia and Andre Vasconcellos
    date: 2016-03-19T20:00:00.000Z
    location: Belo Horizonte - Brazil
    venue: Cafe con letras
    url: ''
  - title: Mike del Ferro trio
    date: 2016-03-28T20:00:00.000Z
    location: Medellin Colombia
    venue: tba
    url: ''
  - title: Mike del Ferro and Mike Boddé pianoduo plus video artist
    date: 2016-04-15T20:00:00.000Z
    location: Amsterdam (NL)
    venue: De Kleine Komedie
    url: www.dekleinekomedie.nl
  - title: Mike del Ferro and Mike Boddé pianoduo plus video artist
    date: 2016-04-16T20:00:00.000Z
    location: Amsterdam (NL)
    venue: De Kleine Komedie
    url: www.dekleinekomedie.nl
  - title: Kuwait Jazz festival
    date: 2016-04-28T20:00:00.000Z
    location: TBA
    venue: Kuwait City
    url: ''
  - title: Mike del Ferro with the Metropole orchestra
    date: 2016-05-08T11:00:00.000Z
    location: Amsterdam (NL)
    venue: 'Concertgebouw, main hall ( 11am! )'
    url: www.concertgebouw.nl
  - title: 'Mike del Ferro / Claron McFadden, stings and horns Metropole'
    date: 2016-06-09T20:00:00.000Z
    location: 'Terneuzen, Zeeland Jazzfestival'
    venue: Scheldetheater
    url: ''
  - title: The music of Queen Mike del Ferro / Jeroen van Veen/ Malgosia Fiebig
    date: 2016-06-11T20:00:00.000Z
    location: Brugge
    venue: Tower
    url: ''
  - title: Mike del Ferro / Jeroen van Veen/ Malgosia Fiebig
    date: 2016-08-22T20:00:00.000Z
    location: Utrecht
    venue: Dom Tower
    url: ''