gigs:
  - title: >-
      Mike del Ferro and Friends, Sunday Afternoon at Splendor, special guest
      Kim Hoorweg
    date: 2018-04-15 16:00:00
    location: Splendor
    venue: Amsterdam (NL)
    url: 'http://www.splendoramsterdam.com'
  - title: 'Summer evening up in the Dom tower, Utrecht'
    date: 2018-08-20 20:00:00
    location: Domtoren
    venue: Utrecht (NL)
    url: 'http://www.klokkenspelvereniging.nl'
  - title: Harp festival with Sitar Master Niladri Kumar
    date: 2018-05-13 15:15:00
    location: Tivoli Vredenburg
    venue: Utrecht
    url: 'http://harpfestival.nl/nl/'
  - title: 'Lisbon Jazz school, artist in residence , 11 & 12 April'
    date: 2018-04-11 13:30:00
    location: tba
    venue: 'Lisbon, Portugal'
    url:
  - title: 'Sunday afternoon Jazz sessions , guest TBA'
    date: 2018-05-06 16:00:00
    location: Splendor
    venue: Amsterdam (NL)
    url: 'http://www.splendoramsterdam.com'
  - title: Mike del Ferro trio
    date: 2018-04-01 15:15:00
    location: Blijburg
    venue: Amsterdam (NL)
    url: 'http://www.blijburg.nl'
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-23 20:15:00
    location: Het Klooster / Theater
    venue: Woerden (NL)
    url: 'http://www.kloosterwoerden.nl'
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-28 08:30:00
    location: Goudse Schouwburg
    venue: Gouda (NL)
    url: 'http://www.goudseschouwburg.nl'
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-30 20:30:00
    location: Griffioen Theater
    venue: Amstelveen
    url: 'http://www.griffioen.vu.nl'
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-31 20:30:00
    location: Parkstad Theater
    venue: Heerlen (NL)
    url: 'http://www.parkstadlimburgtheaters.nl'
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-04-04 20:15:00
    location: De Veste
    venue: Delft (NL)
    url: 'http://www.theaterdeveste.nl'
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-04-07 20:00:00
    location: Schouwburg Odeon
    venue: Zwolle (NL)
    url: 'http://www.zwolsetheaters.nl'
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-04-20 20:30:00
    location: Energiehuis
    venue: Dordrecht
    url: 'http://www.kunstmin.nl'
  - title: Solo concert
    date: 2018-05-19 20:00:00
    location: Munganga
    venue: Amsterdam (NL)
    url: 'http://www.munganga.nl'
  - title: Mike del Ferro & Svenja Staats
    date: 2018-06-10 15:00:00
    location: Ambassador hotel
    venue: Amsterdam
    url:
  - title: Jazz meets Bernstein
    date: 2018-07-24 20:00:00
    location: Albania Jazz festival
    venue: Tirana
    url:
  - title: Mike del Ferro & Mike Boddé - Mike Kwadraat
    date: 2018-11-17 20:30:00
    location: Porgy & Bess
    venue: Terneuzen (NL)
    url: 'http://www.porgyenbess.nl'
  - title: Mike del Ferro trio
    date: 2018-03-20 20:00:00
    location: Luxor theater
    venue: Zutphen (NL)
    url: 'https://www.facebook.com/jazzinluxor'
  - title: Mike del Ferro trio (afternoon concert!)
    date: 2018-03-25 15:00:00
    location: Rosa Spier Huis
    venue: Laren (NL Noord Holland)
    url: 'http://rosaspierhuis.nl'
  - title: Mike del Ferro & Mike Boddé - Mike Kwadraat
    date: 2018-11-20 22:00:00
    location: Luxor
    venue: Zutphen (NL)
    url: 'https://www.facebook.com/jazzinluxor'
  - title: Mike del Ferro-Jazz meets Bernstein
    date: 2018-07-28 20:00:00
    location: TBA
    venue: Tirana (Albania)
    url:
  - title: Solo recital (afternoon!)
    date: 2018-04-21 15:30:00
    location: Het Klavier
    venue: Vorden (NL)
    url: 'https://www.het-klavier.nl'