gigs:
  - title: 'Mike del Ferro and Friends, Sunday Afternoon at Splendor'
    date: 2018-03-18 16:00:00
    location: Splendor
    venue: Amsterdam (NL)
    url: www.splendoramsterdam.com
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-08 20:15:00
    location: De Vereeniging
    venue: Nijmegen (NL)
    url: www.stadsschouwburgendevereeniging.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-16 20:00:00
    location: De Harmonie
    venue: Leeuwarden (NL)
    url: www.harmonie.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-20 20:15:00
    location: De Beun
    venue: Heiloo
    url: www.theaterdebeun.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-23 20:30:00
    location: Stadstheater
    venue: Zoetermeer
    url: www.stadstheater.nl
  - title: 'Duo Mike Bodde & Mike del Ferro, Mike kwadraat'
    date: 2018-02-24 20:30:00
    location: Agora theater
    venue: Lelystad
    url: www.agora-lelystad.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-09 20:30:00
    location: De Lawei
    venue: Drachten
    url: www.lawei.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-16 20:15:00
    location: Singer
    venue: Laren (NL)
    url: www.singerlaren.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-23 20:15:00
    location: Het Klooster / Theater
    venue: Woerden (NL)
    url: www.kloosterwoerden.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-28 08:30:00
    location: Goudse Schouwburg
    venue: Gouda (NL)
    url: www.goudseschouwburg.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-30 20:30:00
    location: Griffioen Theater
    venue: Amstelveen
    url: www.griffioen.vu.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-03-31 20:30:00
    location: Parkstad Theater
    venue: Heerlen (NL)
    url: www.parkstadlimburgtheaters.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-04-04 20:15:00
    location: De Veste
    venue: Delft (NL)
    url: www.theaterdeveste.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-04-07 20:00:00
    location: Schouwburg Odeon
    venue: Zwolle (NL)
    url: www.zwolsetheaters.nl
  - title: 'Mike del Ferro & Mike Boddé, Mike kwadraat'
    date: 2018-04-20 20:30:00
    location: Energiehuis
    venue: Dordrecht
    url: www.kunstmin.nl
  - title: Mike del Ferro trio with Shota Ishikawa & Sebastiaan Kaptein
    date: 2018-03-02 19:00:00
    location: Tenshodo Kobe Kasugano
    venue: Kobe (Japan)
    url: 'http://www.kobetenshodo.com'
  - title: With Eleanor McEvoy - St.Patrick's Irish music Festival
    date: 2018-03-17 20:00:00
    location: Splendor
    venue: Amsterdam (NL)
    url: 'http://www.splendoramsterdam.com'
  - title: Mike del Ferro trio with Shota Ishikawa & Sebastiaan Kaptein
    date: 2018-03-03 17:00:00
    location: Kobe Modern Jazzclub
    venue: Kobe (Japan)
    url: 'https://www.facebook.com/events/1224373214331517/'
  - title: Duo Mike Boddé and Mike del Ferro-Mike Kwadraat
    date: 2018-03-10 20:00:00
    location: Paradox
    venue: Tilburg
    url: www.paradoxtilburg.nl
  - title: Mike del Ferro & Svenja Staats
    date: 2018-06-10 15:00:00
    location: TBA
    venue: TBA
    url:
  - title: 'Mike del Ferro & Kora Master Zoumara Diarra,'
    date: 2018-02-17 20:30:00
    location: Munganga
    venue: Amsterdam
    url: www.munganga.nl
  - title: Mike del Ferro trio with Shota Ishikawa & Sebastiaan Kaptein
    date: 2018-03-04 19:30:00
    location: Request
    venue: Kobe (Japan)
    url: 'https://www.facebook.com/dai.murata.3'
  - title: Jazz meets Bernstein
    date: 2018-07-24 20:00:00
    location: Albania Jazz festival
    venue: Tirana
    url:
  - title: Mike del Ferro & Mike Boddé - Mike Kwadraat
    date: 2018-11-17 20:30:00
    location: Porgy & Bess
    venue: Terneuzen (NL)
    url: www.porgyenbess.nl
  - title: Mike del Ferro trio
    date: 2018-03-20 20:00:00
    location: Luxor theater
    venue: Zutphen (NL)
    url: 'https://www.facebook.com/jazzinluxor'
  - title: Mike del Ferro trio (afternoon concert!)
    date: 2018-03-25 15:00:00
    location: Rosa Spier Huis
    venue: Laren (NL Noord Holland)
    url: 'http://rosaspierhuis.nl'
  - title: Canto Ostinato meets Jazz with Sandra & Jeroen van Veen
    date: 2018-11-20 22:00:00
    location: Luxor
    venue: Zuthpen (NL)
    url: 'https://www.facebook.com/jazzinluxor'
  - title: Mike del Ferro-Jazz meets Bernstein
    date: 2018-07-28 20:00:00
    location: TBA
    venue: Tirana (Albania)
    url: